// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by abidock_mvx code generator

import 'package:abidock_mvx/abidock_mvx.dart';

import '../models/token_payment.dart';

/// Queries queryReturnStruct endpoint.
///
/// #### Read-only:
/// Yes
///
/// #### Returns:
/// - `output`: TokenPayment
///
/// #### Throws:
/// - [NetworkException] if network request fails
/// - [ABIException] if ABI decoding fails
Future<TokenPayment> queryReturnStruct(
  SmartContractController controller,
) async {
  return executeQuery(
    endpointName: 'queryReturnStruct',
    action: () async {
      final result = await controller.query(endpointName: 'queryReturnStruct');

      return TokenPayment.fromAbi(result.typedValues[0]);
    },
  );
}
