// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by abidock_mvx code generator

import 'package:abidock_mvx/abidock_mvx.dart';

import '../models/http_code.dart';

/// Queries queryReturnExplicit endpoint.
///
/// #### Read-only:
/// Yes
///
/// #### Returns:
/// - `output`: HttpCode
///
/// #### Throws:
/// - [NetworkException] if network request fails
/// - [ABIException] if ABI decoding fails
Future<HttpCode> queryReturnExplicit(SmartContractController controller) async {
  return executeQuery(
    endpointName: 'queryReturnExplicit',
    action: () async {
      final result = await controller.query(
        endpointName: 'queryReturnExplicit',
      );

      return HttpCode.fromAbi(result.typedValues[0]);
    },
  );
}
