// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by abidock_mvx code generator

import 'package:abidock_mvx/abidock_mvx.dart';

/// Queries queryReturnMultiTuple endpoint.
///
/// #### Read-only:
/// Yes
///
/// #### Returns:
/// - `output`: u32
/// - `output`: BigUint
/// - `output`: Address
///
/// #### Throws:
/// - [NetworkException] if network request fails
/// - [ABIException] if ABI decoding fails
Future<(int, BigInt, Address)> queryReturnMultiTuple(
  SmartContractController controller,
) async {
  return executeQuery(
    endpointName: 'queryReturnMultiTuple',
    action: () async {
      final result = await controller.query(
        endpointName: 'queryReturnMultiTuple',
      );

      return (
        result.typedValues[0].nativeValue as int,
        result.typedValues[1].nativeValue as BigInt,
        Address.fromBech32(result.typedValues[2].nativeValue as String),
      );
    },
  );
}
