// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by abidock_mvx code generator

import 'package:abidock_mvx/abidock_mvx.dart';

/// Queries queryNothing endpoint.
///
/// #### Read-only:
/// Yes
///
/// #### Throws:
/// - [NetworkException] if network request fails
/// - [ABIException] if ABI decoding fails
Future<void> queryNothing(SmartContractController controller) async {
  return executeQuery(
    endpointName: 'queryNothing',
    action: () async {
      await controller.query(endpointName: 'queryNothing');
    },
  );
}
