// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by abidock_mvx code generator

import 'package:abidock_mvx/abidock_mvx.dart';

import '../models/status.dart';

/// Queries queryReturnEnum endpoint.
///
/// #### Read-only:
/// Yes
///
/// #### Returns:
/// - `output`: Status
///
/// #### Throws:
/// - [NetworkException] if network request fails
/// - [ABIException] if ABI decoding fails
Future<Status> queryReturnEnum(SmartContractController controller) async {
  return executeQuery(
    endpointName: 'queryReturnEnum',
    action: () async {
      final result = await controller.query(endpointName: 'queryReturnEnum');

      return Status.fromAbi(result.typedValues[0]);
    },
  );
}
