// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by abidock_mvx code generator

import 'dart:async';

import 'package:abidock_mvx/abidock_mvx.dart';

import '../models/marker_event.dart';

/// Combined WebSocket stream that fans out every event.
/// Use typed getters, `all`, or `only` to consume events.
final class MultiEventWebSocketStream {
  MultiEventWebSocketStream({
    required this._controller,
    required String websocketUrl,
    Map<String, String> headers = const {},
    bool autoReconnect = true,
    Duration reconnectDelay = const Duration(seconds: 1),
    Duration connectionTimeout = const Duration(seconds: 5),
    Duration pingInterval = const Duration(seconds: 10),
  }) {
    _config = WebSocketEventStreamConfig.byIdentifiers(
      websocketUrl: websocketUrl,
      identifiers: ['marker'],
      contractAddress: _controller.contractAddress,
      abi: _controller.abi,
      headers: headers,
      logger: _controller.logger,
      autoReconnect: autoReconnect,
      reconnectDelay: reconnectDelay,
      connectionTimeout: connectionTimeout,
      pingInterval: pingInterval,
    );

    _stream = WebSocketEventStream(_config);
  }

  final SmartContractController _controller;
  late final WebSocketEventStreamConfig _config;
  late final WebSocketEventStream _stream;

  /// Stream of marker events.
  Stream<MarkerEvent> get marker =>
      EventConverter.filterByIdentifier<MarkerEvent>(
        _stream.events,
        'marker',
        (parsed) => EventConverter.convertEvent<MarkerEvent>(
          parsed,
          MarkerEvent.fromAbi,
          MarkerEvent.type,
        ),
      );

  /// Stream of all events (any type).
  ///
  /// Use type checks to handle different events:
  /// ```dart
  /// stream.all.listen((event) {
  ///   if (event is MarkerEvent) { ... }
  /// });
  /// ```
  Stream<dynamic> get all => _stream.events
      .where((r) => r.parsedEvent != null)
      .map((r) {
        final identifier = r.parsedEvent!.definition.identifier;
        switch (identifier) {
          case 'marker':
            return EventConverter.convertEvent<MarkerEvent>(
              r.parsedEvent!,
              MarkerEvent.fromAbi,
              MarkerEvent.type,
            );
          default:
            return null;
        }
      })
      .where((event) => event != null)
      .cast<dynamic>();

  /// Filter to only specified event types.
  ///
  /// Example:
  /// ```dart
  /// ```
  Stream<dynamic> only(List<Type> eventTypes) {
    return all.where((event) => eventTypes.contains(event.runtimeType));
  }

  /// Stream of connection status changes.
  Stream<WebSocketStatusChange> get statusChanges => _stream.statusChanges;

  /// Stream of WebSocket errors.
  Stream<WebSocketEventError> get errors => _stream.errors;

  /// Connects to WebSocket server.
  Future<void> connect() => _stream.connect();

  /// Disconnects from WebSocket server.
  Future<void> disconnect() => _stream.disconnect();

  /// Dispose resources.
  Future<void> dispose() => _stream.dispose();

  /// Current connection status.
  WebSocketStatus get status => _stream.status;

  /// Pause event streaming.
  void pause() => _stream.pause();

  /// Resume event streaming.
  void resume() => _stream.resume();
}
