// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by abidock_mvx code generator

import 'package:abidock_mvx/abidock_mvx.dart';

import 'http_code.dart';
import 'status.dart';
import 'token_payment.dart';

/// Event model for complex_event.
final class ComplexEvent {
  const ComplexEvent({
    required this.payment,
    required this.status,
    required this.code,
    required this.items,
  });

  final TokenPayment payment;
  final Status status;
  final HttpCode code;
  final List<TokenPayment> items;

  /// ABI type definition.
  static final type = StructType(
    name: 'ComplexEvent',
    fieldDefinitions: [
      FieldDefinition(name: 'payment', type: TokenPayment.type),
      FieldDefinition(name: 'status', type: Status.type),
      FieldDefinition(name: 'code', type: HttpCode.type),
      FieldDefinition(name: 'items', type: ListType(TokenPayment.type)),
    ],
  );

  /// Creates an instance from ABI data.
  factory ComplexEvent.fromAbi(TypedValue value) {
    final struct = value as StructValue;
    return ComplexEvent(
      payment: TokenPayment.fromAbi(struct.getFieldValue('payment')),
      status: Status.fromAbi(struct.getFieldValue('status')),
      code: HttpCode.fromAbi(struct.getFieldValue('code')),
      items: (struct.getFieldValue('items') as ListValue).elements
          .map<TokenPayment>((e) => TokenPayment.fromAbi(e))
          .toList(),
    );
  }

  /// Converts to JSON map.
  Map<String, dynamic> toJson() {
    return {
      'payment': payment.toString(),
      'status': status.toString(),
      'code': code.toString(),
      'items': items.map((e) => e.toString()).toList(),
    };
  }

  @override
  String toString() =>
      'ComplexEvent(payment: $payment, status: $status, code: $code, ...)';

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is ComplexEvent &&
        other.payment == payment &&
        other.status == status &&
        other.code == code &&
        other.items == items;
  }

  @override
  int get hashCode {
    return Object.hash(payment, status, code, items);
  }
}
