// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by abidock_mvx code generator

import 'package:abidock_mvx/abidock_mvx.dart';

/// HttpCode explicit enum.
enum HttpCode {
  ok,
  notFound,
  serverError;

  static final type = ExplicitEnumType(
    name: 'HttpCode',
    variants: [
      const ExplicitEnumVariantDefinition(name: 'Ok', discriminant: 200),
      const ExplicitEnumVariantDefinition(name: 'NotFound', discriminant: 404),
      const ExplicitEnumVariantDefinition(
        name: 'ServerError',
        discriminant: 500,
      ),
    ],
  );

  factory HttpCode.fromAbi(TypedValue value) {
    final nativeValue = value.nativeValue;

    // Handle int discriminant
    if (nativeValue is int) {
      final discriminants = <int>[200, 404, 500];
      final idx = discriminants.indexOf(nativeValue);
      if (idx < 0) {
        throw ArgumentError('Unknown HttpCode discriminant: $nativeValue');
      }
      return HttpCode.values[idx];
    }

    // Handle String variant name
    if (nativeValue is String) {
      return HttpCode.values.firstWhere(
        (v) => v.name.toLowerCase() == nativeValue.toLowerCase(),
        orElse: () =>
            throw ArgumentError('Unknown HttpCode variant: $nativeValue'),
      );
    }

    throw ArgumentError('Invalid HttpCode value: $nativeValue');
  }

  TypedValue toAbi() {
    return type.createValue(index);
  }
}
