// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by abidock_mvx code generator

import 'package:abidock_mvx/abidock_mvx.dart';

/// Event data for marker_only_event.
final class MarkerOnlyEvent {
  const MarkerOnlyEvent();

  /// Creates an instance from ABI data.
  static MarkerOnlyEvent fromAbi(TypedValue value) {
    return const MarkerOnlyEvent();
  }

  Map<String, dynamic> toJson() => {};

  @override
  String toString() => 'MarkerOnlyEvent()';

  @override
  bool operator ==(Object other) => other is MarkerOnlyEvent;

  @override
  int get hashCode => runtimeType.hashCode;

  /// ABI type definition.
  static final type = StructType(name: 'MarkerOnlyEvent', fieldDefinitions: []);
}
