// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by abidock_mvx code generator

import 'package:abidock_mvx/abidock_mvx.dart';

/// Status enum.
enum Status {
  pending,
  active,
  closed;

  static final type = EnumType(
    name: 'Status',
    variants: [
      const EnumVariantDefinition(name: 'Pending', discriminant: 0),
      const EnumVariantDefinition(name: 'Active', discriminant: 1),
      const EnumVariantDefinition(name: 'Closed', discriminant: 2),
    ],
  );

  factory Status.fromAbi(TypedValue value) {
    final nativeValue = value.nativeValue;

    // Handle int discriminant
    if (nativeValue is int) {
      final discriminants = <int>[0, 1, 2];
      final idx = discriminants.indexOf(nativeValue);
      if (idx < 0) {
        throw ArgumentError('Unknown Status discriminant: $nativeValue');
      }
      return Status.values[idx];
    }

    // Handle String variant name (from event parsing)
    if (nativeValue is String) {
      return Status.values.firstWhere(
        (v) => v.name.toLowerCase() == nativeValue.toLowerCase(),
        orElse: () =>
            throw ArgumentError('Unknown Status variant: $nativeValue'),
      );
    }

    throw ArgumentError('Invalid Status value: $nativeValue');
  }

  TypedValue toAbi() {
    return type.createValue(index);
  }
}
