// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by abidock_mvx code generator

import 'package:abidock_mvx/abidock_mvx.dart';

/// TokenPayment model.
class TokenPayment {
  const TokenPayment({
    required this.tokenIdentifier,
    required this.tokenNonce,
    required this.amount,
  });

  final TokenIdentifier tokenIdentifier;
  final BigInt tokenNonce;
  final BigInt amount;

  static final StructType type = StructType(
    name: 'TokenPayment',
    fieldDefinitions: [
      FieldDefinition(name: 'token_identifier', type: TokenIdentifierType.type),
      FieldDefinition(name: 'token_nonce', type: U64Type.type),
      FieldDefinition(name: 'amount', type: BigUIntType.type),
    ],
  );

  factory TokenPayment.fromAbi(TypedValue value) {
    final struct = value as StructValue;
    return TokenPayment(
      tokenIdentifier: TokenIdentifier(
        struct.getFieldValue('token_identifier').nativeValue as String,
      ),
      tokenNonce: struct.getFieldValue('token_nonce').nativeValue as BigInt,
      amount: struct.getFieldValue('amount').nativeValue as BigInt,
    );
  }

  TypedValue toAbi() {
    return type.createValue({
      'token_identifier': tokenIdentifier.value,
      'token_nonce': tokenNonce,
      'amount': amount,
    });
  }

  Map<String, dynamic> toJson() {
    return {
      'token_identifier': tokenIdentifier.value,
      'token_nonce': tokenNonce.toString(),
      'amount': amount.toString(),
    };
  }
}
