// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by abidock_mvx code generator

import 'package:abidock_mvx/abidock_mvx.dart';

/// Event model for transfer_event.
final class TransferEvent {
  const TransferEvent({
    required this.from,
    required this.to,
    required this.amount,
    required this.token,
  });

  final Address from;
  final Address to;
  final BigInt amount;
  final TokenIdentifier token;

  /// ABI type definition.
  static final type = StructType(
    name: 'TransferEvent',
    fieldDefinitions: [
      FieldDefinition(name: 'from', type: AddressType.type),
      FieldDefinition(name: 'to', type: AddressType.type),
      FieldDefinition(name: 'amount', type: BigUIntType.type),
      FieldDefinition(name: 'token', type: TokenIdentifierType.type),
    ],
  );

  /// Creates an instance from ABI data.
  factory TransferEvent.fromAbi(TypedValue value) {
    final struct = value as StructValue;
    return TransferEvent(
      from: Address.fromBech32(
        struct.getFieldValue('from').nativeValue as String,
      ),
      to: Address.fromBech32(struct.getFieldValue('to').nativeValue as String),
      amount: struct.getFieldValue('amount').nativeValue as BigInt,
      token: TokenIdentifier(
        struct.getFieldValue('token').nativeValue as String,
      ),
    );
  }

  /// Converts to JSON map.
  Map<String, dynamic> toJson() {
    return {
      'from': from.bech32,
      'to': to.bech32,
      'amount': amount.toString(),
      'token': token.value,
    };
  }

  @override
  String toString() =>
      'TransferEvent(from: $from, to: $to, amount: $amount, ...)';

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is TransferEvent &&
        other.from == from &&
        other.to == to &&
        other.amount == amount &&
        other.token == token;
  }

  @override
  int get hashCode {
    return Object.hash(from, to, amount, token);
  }
}
