// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by abidock_mvx code generator

import 'package:abidock_mvx/abidock_mvx.dart';

/// Queries nestedOption endpoint.
///
/// #### Read-only:
/// Yes
///
/// #### Parameters:
/// - `x`: Option&lt;Option&lt;u32&gt;&gt;
///
/// #### Returns:
/// - `output`: Option&lt;List&lt;BigUint&gt;&gt;
///
/// #### Throws:
/// - [NetworkException] if network request fails
/// - [ABIException] if ABI decoding fails
Future<List<BigInt>?> nestedOption(
  SmartContractController controller,
  int? x,
) async {
  final xValue = OptionType(OptionType(U32Type.type)).createValue(x);

  return executeQuery(
    endpointName: 'nestedOption',
    action: () async {
      final result = await controller.query(
        endpointName: 'nestedOption',
        arguments: [xValue],
      );

      return (() {
        final v = result.typedValues[0] as OptionValue;
        return v.value == null
            ? null
            : (v.value! as ListValue).elements
                  .map<BigInt>((e) => e.nativeValue as BigInt)
                  .toList();
      })();
    },
  );
}
