// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by abidock_mvx code generator

import 'package:abidock_mvx/abidock_mvx.dart';

/// Queries returnListOfList endpoint.
///
/// #### Read-only:
/// Yes
///
/// #### Returns:
/// - `output`: List&lt;List&lt;BigUint&gt;&gt;
///
/// #### Throws:
/// - [NetworkException] if network request fails
/// - [ABIException] if ABI decoding fails
Future<List<List<BigInt>>> returnListOfList(
  SmartContractController controller,
) async {
  return executeQuery(
    endpointName: 'returnListOfList',
    action: () async {
      final result = await controller.query(endpointName: 'returnListOfList');

      return (result.typedValues[0] as ListValue).elements
          .map<List<BigInt>>(
            (e) => (e as ListValue).elements
                .map<BigInt>((e) => e.nativeValue as BigInt)
                .toList(),
          )
          .toList();
    },
  );
}
