// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by abidock_mvx code generator

import 'package:abidock_mvx/abidock_mvx.dart';

/// EmptyStruct model.
class EmptyStruct {
  const EmptyStruct();

  static final StructType type = StructType(
    name: 'EmptyStruct',
    fieldDefinitions: [],
  );

  factory EmptyStruct.fromAbi(TypedValue value) {
    value as StructValue;
    return const EmptyStruct();
  }

  TypedValue toAbi() {
    return type.createValue({});
  }

  Map<String, dynamic> toJson() {
    return {};
  }
}
