// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by abidock_mvx code generator

import 'package:abidock_mvx/abidock_mvx.dart';

/// Event data for marker.
final class MarkerEvent {
  const MarkerEvent();

  /// Creates an instance from ABI data.
  static MarkerEvent fromAbi(TypedValue value) {
    return const MarkerEvent();
  }

  Map<String, dynamic> toJson() => {};

  @override
  String toString() => 'MarkerEvent()';

  @override
  bool operator ==(Object other) => other is MarkerEvent;

  @override
  int get hashCode => runtimeType.hashCode;

  /// ABI type definition.
  static final type = StructType(name: 'MarkerEvent', fieldDefinitions: []);
}
