// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by abidock_mvx code generator

import 'package:abidock_mvx/abidock_mvx.dart';

/// Node model.
class Node {
  const Node({required this.id, required this.label, required this.children});

  final int id;
  final String label;
  final List<Node> children;

  static final StructType type = StructType(
    name: 'Node',
    fieldDefinitions: [
      FieldDefinition(name: 'id', type: U32Type.type),
      FieldDefinition(name: 'label', type: StringType.type),
      FieldDefinition(name: 'children', type: ListType(Node.type)),
    ],
  );

  factory Node.fromAbi(TypedValue value) {
    final struct = value as StructValue;
    return Node(
      id: struct.getFieldValue('id').nativeValue as int,
      label: struct.getFieldValue('label').nativeValue as String,
      children: (struct.getFieldValue('children') as ListValue).elements
          .map<Node>((e) => Node.fromAbi(e))
          .toList(),
    );
  }

  TypedValue toAbi() {
    return type.createValue({
      'id': id,
      'label': label,
      'children': children.map((e) => e.toAbi()).toList(),
    });
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'label': label,
      'children': children.map((e) => e.toJson()).toList(),
    };
  }
}
