// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by abidock_mvx code generator

import 'dart:async';

import 'package:abidock_mvx/abidock_mvx.dart';

import '../../models/complex_event.dart';

/// HTTP polling stream for complex_event events.
///
/// #### Event Fields:
/// - `payment`: TokenPayment
/// - `status`: Status
/// - `code`: HttpCode
/// - `items`: List&lt;TokenPayment&gt;
final class ComplexEventPollingStream {
  const ComplexEventPollingStream(this.controller);

  final SmartContractController controller;

  /// Starts polling for complex_event events.
  Stream<ComplexEvent> call({
    Duration pollingInterval = const Duration(seconds: 10),
    String? startFrom,
  }) {
    return controller
        .streamEvents(
          eventIdentifier: 'complex_event',
          pollingInterval: pollingInterval,
          startFrom: startFrom,
        )
        .map((parsedEvent) {
          final eventStruct = parsedEvent.getValueByName('complex_event');
          if (eventStruct == null) {
            throw StateError('Event struct not found in parsed event');
          }
          return ComplexEvent.fromAbi(eventStruct);
        });
  }
}
