// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by abidock_mvx code generator

import 'dart:async';

import 'package:abidock_mvx/abidock_mvx.dart';

import '../../models/marker_only_event.dart';

/// HTTP polling stream for marker_only_event events.
///
final class MarkerOnlyEventPollingStream {
  const MarkerOnlyEventPollingStream(this.controller);

  final SmartContractController controller;

  /// Starts polling for marker_only_event events.
  Stream<MarkerOnlyEvent> call({
    Duration pollingInterval = const Duration(seconds: 10),
    String? startFrom,
  }) {
    return controller
        .streamEvents(
          eventIdentifier: 'marker_only_event',
          pollingInterval: pollingInterval,
          startFrom: startFrom,
        )
        .map((parsedEvent) {
          final decoded = EventConverter.convertEvent<MarkerOnlyEvent>(
            parsedEvent,
            MarkerOnlyEvent.fromAbi,
            MarkerOnlyEvent.type,
          );
          if (decoded == null) {
            throw StateError('Failed to decode marker_only_event event');
          }
          return decoded;
        });
  }
}
