// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by abidock_mvx code generator

import 'dart:async';

import 'package:abidock_mvx/abidock_mvx.dart';

import '../../models/transfer_event.dart';

/// HTTP polling stream for transfer_event events.
///
/// #### Event Fields:
/// - `from`: Address (indexed)
/// - `to`: Address (indexed)
/// - `amount`: BigUint
/// - `token`: TokenIdentifier (indexed)
final class TransferEventPollingStream {
  const TransferEventPollingStream(this.controller);

  final SmartContractController controller;

  /// Starts polling for transfer_event events.
  Stream<TransferEvent> call({
    Duration pollingInterval = const Duration(seconds: 10),
    String? startFrom,
  }) {
    return controller
        .streamEvents(
          eventIdentifier: 'transfer_event',
          pollingInterval: pollingInterval,
          startFrom: startFrom,
        )
        .map((parsedEvent) {
          final decoded = EventConverter.convertEvent<TransferEvent>(
            parsedEvent,
            TransferEvent.fromAbi,
            TransferEvent.type,
          );
          if (decoded == null) {
            throw StateError('Failed to decode transfer_event event');
          }
          return decoded;
        });
  }
}
