// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by abidock_mvx code generator

import 'dart:async';

import 'package:abidock_mvx/abidock_mvx.dart';

import '../../models/marker_event.dart';

/// HTTP polling stream for marker events.
///
final class MarkerPollingStream {
  const MarkerPollingStream(this.controller);

  final SmartContractController controller;

  /// Starts polling for marker events.
  Stream<MarkerEvent> call({
    Duration pollingInterval = const Duration(seconds: 10),
    String? startFrom,
  }) {
    return controller
        .streamEvents(
          eventIdentifier: 'marker',
          pollingInterval: pollingInterval,
          startFrom: startFrom,
        )
        .map((parsedEvent) {
          final eventStruct = parsedEvent.getValueByName('marker_event');
          if (eventStruct == null) {
            throw StateError('Event struct not found in parsed event');
          }
          return MarkerEvent.fromAbi(eventStruct);
        });
  }
}
