// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by abidock_mvx code generator

import 'package:abidock_mvx/abidock_mvx.dart';

/// Transfers NFT/SFT tokens.
///
/// Creates and signs a transaction for transferring non-fungible
/// or semi-fungible tokens. Requires token ID, nonce, and amount.
///
/// Example:
/// ```dart
/// final provider = GatewayProvider(
///   gatewayUrl: 'https://gateway.multiversx.com',
/// );
/// final tx = await nft(
///   provider,
///   sender: alice,
///   nonce: nonce,
///   receiver: bobAddress,
///   tokenId: 'NFT-abc123',
///   tokenNonce: 42,
///   amount: BigInt.one,
/// );
/// await provider.sendTransaction(tx);
/// ```
Future<Transaction> nft(
  NetworkProvider provider,
  IAccount sender,
  Nonce nonce,
  Address receiver,
  String tokenId,
  int tokenNonce,
  BigInt amount, {
  Address? relayer,
  Address? guardian,
  GasLimit? gasLimit,
}) async {
  final transfersCtrl = TransfersController(chainId: provider.chainId);

  final tx = await transfersCtrl.createTransactionForTokenTransfer(
    sender,
    nonce,
    TokenTransferInput(
      receiver: receiver,
      transfers: [
        TokenTransfer.nonFungible(
          tokenIdentifier: tokenId,
          nonce: tokenNonce,
          amount: amount,
        ),
      ],
    ),
    baseOptions: gasLimit != null || relayer != null || guardian != null
        ? BaseControllerInput(
            gasLimit: gasLimit,
            relayer: relayer,
            guardian: guardian,
          )
        : const BaseControllerInput(),
  );

  return tx;
}
