// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by abidock_mvx code generator

import 'dart:async';

import 'package:abidock_mvx/abidock_mvx.dart';

import '../models/add_liquidity_event_data.dart';
import '../models/remove_liquidity_event_data.dart';
import '../models/swap_event_data.dart';
import '../models/swap_no_fee_and_forward_event_data.dart';

/// HTTP polling stream that fans out every event.
/// Runs one polling loop and exposes typed getters.
final class MultiEventPollingStream {
  MultiEventPollingStream({
    required this.controller,
    Duration pollingInterval = const Duration(seconds: 10),
    String? startFrom,
  }) {
    _baseStream = controller
        .streamAllEvents(pollingInterval: pollingInterval, startFrom: startFrom)
        .asBroadcastStream(onCancel: (sub) => sub.cancel());
  }

  final SmartContractController controller;
  late final Stream<ParsedEvent> _baseStream;

  /// Stream of swap events.
  Stream<SwapEventData> get swap => _baseStream
      .where((event) => event.definition.identifier == 'swap')
      .map((parsedEvent) {
        final eventStruct = parsedEvent.getValueByName('swap_event');
        if (eventStruct == null) {
          throw StateError('Event struct not found in parsed event');
        }
        return SwapEventData.fromAbi(eventStruct);
      });

  /// Stream of swap_no_fee_and_forward events.
  Stream<SwapNoFeeAndForwardEventData> get swapNoFeeAndForward => _baseStream
      .where(
        (event) => event.definition.identifier == 'swap_no_fee_and_forward',
      )
      .map((parsedEvent) {
        final eventStruct = parsedEvent.getValueByName(
          'swap_no_fee_and_forward_event',
        );
        if (eventStruct == null) {
          throw StateError('Event struct not found in parsed event');
        }
        return SwapNoFeeAndForwardEventData.fromAbi(eventStruct);
      });

  /// Stream of add_liquidity events.
  Stream<AddLiquidityEventData> get addLiquidity => _baseStream
      .where((event) => event.definition.identifier == 'add_liquidity')
      .map((parsedEvent) {
        final eventStruct = parsedEvent.getValueByName('add_liquidity_event');
        if (eventStruct == null) {
          throw StateError('Event struct not found in parsed event');
        }
        return AddLiquidityEventData.fromAbi(eventStruct);
      });

  /// Stream of remove_liquidity events.
  Stream<RemoveLiquidityEventData> get removeLiquidity => _baseStream
      .where((event) => event.definition.identifier == 'remove_liquidity')
      .map((parsedEvent) {
        final eventStruct = parsedEvent.getValueByName(
          'remove_liquidity_event',
        );
        if (eventStruct == null) {
          throw StateError('Event struct not found in parsed event');
        }
        return RemoveLiquidityEventData.fromAbi(eventStruct);
      });

  /// Stream of all event types as dynamic objects.
  ///
  /// Use type checking to handle different event types:
  /// ```dart
  /// stream.all.listen((event) {
  ///   if (event is SwapEventData) {
  ///     // Handle swap
  ///   }
  ///   else if (event is SwapNoFeeAndForwardEventData) {
  ///     // Handle swap_no_fee_and_forward
  ///   }
  ///   else if (event is AddLiquidityEventData) {
  ///     // Handle add_liquidity
  ///   }
  /// });
  /// ```
  Stream<dynamic> get all {
    return _baseStream
        .asyncMap((parsedEvent) async {
          final identifier = parsedEvent.definition.identifier;
          switch (identifier) {
            case 'swap':
              final struct = parsedEvent.getValueByName('swap_event');
              return struct != null ? SwapEventData.fromAbi(struct) : null;
            case 'swap_no_fee_and_forward':
              final struct = parsedEvent.getValueByName(
                'swap_no_fee_and_forward_event',
              );
              return struct != null
                  ? SwapNoFeeAndForwardEventData.fromAbi(struct)
                  : null;
            case 'add_liquidity':
              final struct = parsedEvent.getValueByName('add_liquidity_event');
              return struct != null
                  ? AddLiquidityEventData.fromAbi(struct)
                  : null;
            case 'remove_liquidity':
              final struct = parsedEvent.getValueByName(
                'remove_liquidity_event',
              );
              return struct != null
                  ? RemoveLiquidityEventData.fromAbi(struct)
                  : null;
            default:
              return null;
          }
        })
        .where((event) => event != null)
        .cast<dynamic>();
  }

  /// Stream filtered to only specified event types.
  ///
  /// #### Example
  /// ```dart
  /// stream.only([SwapEvent, SwapNoFeeAndForwardEvent]).listen((event) {
  ///   // Only swap and swap_no_fee_and_forward events
  /// });
  /// ```
  Stream<dynamic> only(List<Type> types) {
    return all.where((event) => types.contains(event.runtimeType));
  }
}
