// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by abidock_mvx code generator

import 'dart:async';

import 'package:abidock_mvx/abidock_mvx.dart';

import '../models/add_liquidity_event_data.dart';
import '../models/remove_liquidity_event_data.dart';
import '../models/swap_event_data.dart';
import '../models/swap_no_fee_and_forward_event_data.dart';

/// HTTP polling stream that fans out every event.
/// Runs one polling loop and exposes typed getters.
final class MultiEventPollingStream {
  MultiEventPollingStream({
    required this.controller,
    Duration pollingInterval = const Duration(seconds: 10),
    String? startFrom,
  }) {
    _baseStream = controller
        .streamAllEvents(pollingInterval: pollingInterval, startFrom: startFrom)
        .asBroadcastStream(onCancel: (sub) => sub.cancel());
  }

  final SmartContractController controller;
  late final Stream<ParsedEvent> _baseStream;

  /// Stream of swap events.
  Stream<SwapEventData> get swap => _baseStream
      .where((event) => event.definition.identifier == 'swap')
      .map((parsedEvent) {
        final decoded = EventConverter.convertEvent<SwapEventData>(
          parsedEvent,
          SwapEventData.fromAbi,
          SwapEventData.type,
        );
        if (decoded == null) {
          throw StateError('Failed to decode swap event');
        }
        return decoded;
      });

  /// Stream of swap_no_fee_and_forward events.
  Stream<SwapNoFeeAndForwardEventData> get swapNoFeeAndForward => _baseStream
      .where(
        (event) => event.definition.identifier == 'swap_no_fee_and_forward',
      )
      .map((parsedEvent) {
        final decoded =
            EventConverter.convertEvent<SwapNoFeeAndForwardEventData>(
              parsedEvent,
              SwapNoFeeAndForwardEventData.fromAbi,
              SwapNoFeeAndForwardEventData.type,
            );
        if (decoded == null) {
          throw StateError('Failed to decode swap_no_fee_and_forward event');
        }
        return decoded;
      });

  /// Stream of add_liquidity events.
  Stream<AddLiquidityEventData> get addLiquidity => _baseStream
      .where((event) => event.definition.identifier == 'add_liquidity')
      .map((parsedEvent) {
        final decoded = EventConverter.convertEvent<AddLiquidityEventData>(
          parsedEvent,
          AddLiquidityEventData.fromAbi,
          AddLiquidityEventData.type,
        );
        if (decoded == null) {
          throw StateError('Failed to decode add_liquidity event');
        }
        return decoded;
      });

  /// Stream of remove_liquidity events.
  Stream<RemoveLiquidityEventData> get removeLiquidity => _baseStream
      .where((event) => event.definition.identifier == 'remove_liquidity')
      .map((parsedEvent) {
        final decoded = EventConverter.convertEvent<RemoveLiquidityEventData>(
          parsedEvent,
          RemoveLiquidityEventData.fromAbi,
          RemoveLiquidityEventData.type,
        );
        if (decoded == null) {
          throw StateError('Failed to decode remove_liquidity event');
        }
        return decoded;
      });

  /// Stream of all event types as dynamic objects.
  ///
  /// Use type checking to handle different event types:
  /// ```dart
  /// stream.all.listen((event) {
  ///   if (event is SwapEventData) {
  ///     // Handle swap
  ///   }
  ///   else if (event is SwapNoFeeAndForwardEventData) {
  ///     // Handle swap_no_fee_and_forward
  ///   }
  ///   else if (event is AddLiquidityEventData) {
  ///     // Handle add_liquidity
  ///   }
  /// });
  /// ```
  Stream<dynamic> get all {
    return _baseStream
        .asyncMap((parsedEvent) async {
          final identifier = parsedEvent.definition.identifier;
          switch (identifier) {
            case 'swap':
              return EventConverter.convertEvent<SwapEventData>(
                parsedEvent,
                SwapEventData.fromAbi,
                SwapEventData.type,
              );
            case 'swap_no_fee_and_forward':
              return EventConverter.convertEvent<SwapNoFeeAndForwardEventData>(
                parsedEvent,
                SwapNoFeeAndForwardEventData.fromAbi,
                SwapNoFeeAndForwardEventData.type,
              );
            case 'add_liquidity':
              return EventConverter.convertEvent<AddLiquidityEventData>(
                parsedEvent,
                AddLiquidityEventData.fromAbi,
                AddLiquidityEventData.type,
              );
            case 'remove_liquidity':
              return EventConverter.convertEvent<RemoveLiquidityEventData>(
                parsedEvent,
                RemoveLiquidityEventData.fromAbi,
                RemoveLiquidityEventData.type,
              );
            default:
              return null;
          }
        })
        .where((event) => event != null)
        .cast<dynamic>();
  }

  /// Stream filtered to only specified event types.
  ///
  /// #### Example
  /// ```dart
  /// stream.only([SwapEvent, SwapNoFeeAndForwardEvent]).listen((event) {
  ///   // Only swap and swap_no_fee_and_forward events
  /// });
  /// ```
  Stream<dynamic> only(List<Type> types) {
    return all.where((event) => types.contains(event.runtimeType));
  }
}
