// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by abidock_mvx code generator

import 'dart:async';

import 'package:abidock_mvx/abidock_mvx.dart';

import '../../models/remove_liquidity_event_data.dart';

/// HTTP polling stream for remove_liquidity events.
///
/// #### Event Fields:
/// - `firstToken`: TokenIdentifier (indexed)
/// - `secondToken`: TokenIdentifier (indexed)
/// - `caller`: Address (indexed)
/// - `epoch`: u64 (indexed)
/// - `removeLiquidityEvent`: RemoveLiquidityEvent
final class RemoveLiquidityPollingStream {
  const RemoveLiquidityPollingStream(this.controller);

  final SmartContractController controller;

  /// Starts polling for remove_liquidity events.
  Stream<RemoveLiquidityEventData> call({
    Duration pollingInterval = const Duration(seconds: 10),
    String? startFrom,
  }) {
    return controller
        .streamEvents(
          eventIdentifier: 'remove_liquidity',
          pollingInterval: pollingInterval,
          startFrom: startFrom,
        )
        .map((parsedEvent) {
          final decoded = EventConverter.convertEvent<RemoveLiquidityEventData>(
            parsedEvent,
            RemoveLiquidityEventData.fromAbi,
            RemoveLiquidityEventData.type,
          );
          if (decoded == null) {
            throw StateError('Failed to decode remove_liquidity event');
          }
          return decoded;
        });
  }
}
