// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by abidock_mvx code generator

import 'dart:async';

import 'package:abidock_mvx/abidock_mvx.dart';

import '../../models/swap_event_data.dart';

/// HTTP polling stream for swap events.
///
/// #### Event Fields:
/// - `tokenIn`: TokenIdentifier (indexed)
/// - `tokenOut`: TokenIdentifier (indexed)
/// - `caller`: Address (indexed)
/// - `epoch`: u64 (indexed)
/// - `swapEvent`: SwapEvent
final class SwapPollingStream {
  const SwapPollingStream(this.controller);

  final SmartContractController controller;

  /// Starts polling for swap events.
  Stream<SwapEventData> call({
    Duration pollingInterval = const Duration(seconds: 10),
    String? startFrom,
  }) {
    return controller
        .streamEvents(
          eventIdentifier: 'swap',
          pollingInterval: pollingInterval,
          startFrom: startFrom,
        )
        .map((parsedEvent) {
          final decoded = EventConverter.convertEvent<SwapEventData>(
            parsedEvent,
            SwapEventData.fromAbi,
            SwapEventData.type,
          );
          if (decoded == null) {
            throw StateError('Failed to decode swap event');
          }
          return decoded;
        });
  }
}
