// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by abidock_mvx code generator

import 'dart:async';

import 'package:abidock_mvx/abidock_mvx.dart';

import '../../models/swap_no_fee_and_forward_event_data.dart';

/// HTTP polling stream for swap_no_fee_and_forward events.
///
/// #### Event Fields:
/// - `tokenIdOut`: TokenIdentifier (indexed)
/// - `caller`: Address (indexed)
/// - `epoch`: u64 (indexed)
/// - `swapNoFeeAndForwardEvent`: SwapNoFeeAndForwardEvent
final class SwapNoFeeAndForwardPollingStream {
  const SwapNoFeeAndForwardPollingStream(this.controller);

  final SmartContractController controller;

  /// Starts polling for swap_no_fee_and_forward events.
  Stream<SwapNoFeeAndForwardEventData> call({
    Duration pollingInterval = const Duration(seconds: 10),
    String? startFrom,
  }) {
    return controller
        .streamEvents(
          eventIdentifier: 'swap_no_fee_and_forward',
          pollingInterval: pollingInterval,
          startFrom: startFrom,
        )
        .map((parsedEvent) {
          final eventStruct = parsedEvent.getValueByName(
            'swap_no_fee_and_forward_event',
          );
          if (eventStruct == null) {
            throw StateError('Event struct not found in parsed event');
          }
          return SwapNoFeeAndForwardEventData.fromAbi(eventStruct);
        });
  }
}
