// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by abidock_mvx code generator

import 'package:abidock_mvx/abidock_mvx.dart';

/// Calls setupFeesCollector endpoint.
///
/// `fees_collector_cut_percentage` of the special fees are sent to the fees_collector_address SC
///
/// For example, if special fees is 5%, and fees_collector_cut_percentage is 10%,
/// then of the 5%, 10% are reserved, and only the rest are split between other pair contracts.
///
/// #### Parameters:
/// - `feesCollectorAddress`: Address
/// - `feesCollectorCutPercentage`: u64
///
/// #### Throws:
/// - [NetworkException] if network request fails
/// - [EndpointNotFoundException] if endpoint not found in ABI
/// - [ArgumentEncodingException] if ABI encoding fails
Future<Transaction> setupFeesCollector(
  SmartContractController controller,
  IAccount sender,
  Nonce nonce,
  Address feesCollectorAddress,
  BigInt feesCollectorCutPercentage, {
  Address? relayer,
  Address? guardian,
  Balance? value,
}) async {
  final factory = SmartContractCallFactory(
    contractAddress: controller.contractAddress,
    abi: controller.abi,
    chainId: controller.networkProvider.chainId,
  );
  final probeTx = factory.createCall(
    sender: sender.address,
    nonce: nonce,
    endpointName: 'setupFeesCollector',
    arguments: <dynamic>[
      feesCollectorAddress.bech32,
      feesCollectorCutPercentage,
    ],
    gasLimit: const GasLimit(600000000),
    value: value,
  );
  final gasLimit = await simulateGas(probeTx, controller.networkProvider);

  return controller.call(
    account: sender,
    nonce: nonce,
    endpointName: 'setupFeesCollector',
    arguments: <dynamic>[
      feesCollectorAddress.bech32,
      feesCollectorCutPercentage,
    ],
    value: value,
    options: BaseControllerInput(
      gasLimit: gasLimit,
      relayer: relayer,
      guardian: guardian,
    ),
  );
}

/// Builds an unsigned transaction for setupFeesCollector endpoint.
/// #### Parameters:
/// - `feesCollectorAddress`: Address
/// - `feesCollectorCutPercentage`: u64
///
/// #### Returns:
/// Future<[Transaction]> - Unsigned transaction with auto-estimated gas
///
/// #### Example:
/// ```dart
/// // Build unsigned transactions for batch signing
/// final tx1 = await setupFeesCollectorUnsigned(factory, provider, sender, nonce1, ...);
/// final tx2 = await anotherUnsigned(factory2, provider, sender, nonce2, ...);
///
/// // Sign batch
/// final sigs = await account.signTransactions([tx1, tx2]);
///
/// // Apply signatures and send
/// final signed1 = tx1.copyWith(newSignature: Signature.fromUint8List(sigs[0]));
/// final signed2 = tx2.copyWith(newSignature: Signature.fromUint8List(sigs[1]));
/// await provider.sendTransactions([signed1, signed2]);
/// ```
Future<Transaction> setupFeesCollectorUnsigned(
  SmartContractCallFactory factory,
  NetworkProvider networkProvider,
  Address sender,
  Nonce nonce,
  Address feesCollectorAddress,
  BigInt feesCollectorCutPercentage, {
  Balance? value,
}) async {
  final tx = factory.createCall(
    sender: sender,
    nonce: nonce,
    endpointName: 'setupFeesCollector',
    arguments: <dynamic>[
      feesCollectorAddress.bech32,
      feesCollectorCutPercentage,
    ],
    gasLimit: const GasLimit(600000000),
    value: value,
  );

  final gasLimit = await simulateGas(tx, networkProvider);

  return tx.copyWith(newGasLimit: gasLimit);
}
