// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by abidock_mvx code generator

import 'dart:typed_data';

import 'package:abidock_mvx/abidock_mvx.dart';

import '../models/token_payment.dart';

/// Calls collectionSoup endpoint.
///
/// #### Parameters:
/// - `aList`: List&lt;u32&gt;
/// - `aArr3`: ManagedByteArray&lt;3&gt;
/// - `aOpt`: Option&lt;BigUint&gt;
/// - `aOptional`: optional&lt;TokenIdentifier&gt;
/// - `aTuple`: tuple&lt;u32,Address&gt;
/// - `aVariadic`: variadic&lt;u32&gt;
/// - `aMulti`: multi&lt;u32,Address&gt;
/// - `aNestedList`: List&lt;Option&lt;BigUint&gt;&gt;
/// - `aListStruct`: List&lt;TokenPayment&gt;
///
/// #### Throws:
/// - [NetworkException] if network request fails
/// - [EndpointNotFoundException] if endpoint not found in ABI
/// - [ArgumentEncodingException] if ABI encoding fails
Future<Transaction> collectionSoup(
  SmartContractController controller,
  IAccount sender,
  Nonce nonce,
  List<int> aList,
  Uint8List aArr3,
  BigInt? aOpt,
  TokenIdentifier? aOptional,
  (int, Address) aTuple,
  List<int> aVariadic,
  (int, Address) aMulti,
  List<BigInt?> aNestedList,
  List<TokenPayment> aListStruct, {
  Address? relayer,
  Address? guardian,
  Balance? value,
}) async {
  final factory = SmartContractCallFactory(
    contractAddress: controller.contractAddress,
    abi: controller.abi,
    chainId: controller.networkProvider.chainId,
  );
  final probeTx = factory.createCall(
    sender: sender.address,
    nonce: nonce,
    endpointName: 'collectionSoup',
    arguments: <dynamic>[
      aList,
      aArr3,
      aOpt,
      aOptional,
      <dynamic>[aTuple.$1, aTuple.$2],
      aVariadic,
      <dynamic>[aMulti.$1, aMulti.$2],
      aNestedList,
      aListStruct,
    ],
    gasLimit: const GasLimit(600000000),
    value: value,
  );
  final gasLimit = await simulateGas(probeTx, controller.networkProvider);

  return controller.call(
    account: sender,
    nonce: nonce,
    endpointName: 'collectionSoup',
    arguments: <dynamic>[
      aList,
      aArr3,
      aOpt,
      aOptional,
      <dynamic>[aTuple.$1, aTuple.$2],
      aVariadic,
      <dynamic>[aMulti.$1, aMulti.$2],
      aNestedList,
      aListStruct,
    ],
    value: value,
    options: BaseControllerInput(
      gasLimit: gasLimit,
      relayer: relayer,
      guardian: guardian,
    ),
  );
}

/// Builds an unsigned transaction for collectionSoup endpoint.
/// #### Parameters:
/// - `aList`: List&lt;u32&gt;
/// - `aArr3`: ManagedByteArray&lt;3&gt;
/// - `aOpt`: Option&lt;BigUint&gt;
/// - `aOptional`: optional&lt;TokenIdentifier&gt;
/// - `aTuple`: tuple&lt;u32,Address&gt;
/// - `aVariadic`: variadic&lt;u32&gt;
/// - `aMulti`: multi&lt;u32,Address&gt;
/// - `aNestedList`: List&lt;Option&lt;BigUint&gt;&gt;
/// - `aListStruct`: List&lt;TokenPayment&gt;
///
/// #### Returns:
/// Future<[Transaction]> - Unsigned transaction with auto-estimated gas
///
/// #### Example:
/// ```dart
/// // Build unsigned transactions for batch signing
/// final tx1 = await collectionSoupUnsigned(factory, provider, sender, nonce1, ...);
/// final tx2 = await anotherUnsigned(factory2, provider, sender, nonce2, ...);
///
/// // Sign batch
/// final sigs = await account.signTransactions([tx1, tx2]);
///
/// // Apply signatures and send
/// final signed1 = tx1.copyWith(newSignature: Signature.fromUint8List(sigs[0]));
/// final signed2 = tx2.copyWith(newSignature: Signature.fromUint8List(sigs[1]));
/// await provider.sendTransactions([signed1, signed2]);
/// ```
Future<Transaction> collectionSoupUnsigned(
  SmartContractCallFactory factory,
  NetworkProvider networkProvider,
  Address sender,
  Nonce nonce,
  List<int> aList,
  Uint8List aArr3,
  BigInt? aOpt,
  TokenIdentifier? aOptional,
  (int, Address) aTuple,
  List<int> aVariadic,
  (int, Address) aMulti,
  List<BigInt?> aNestedList,
  List<TokenPayment> aListStruct, {
  Balance? value,
}) async {
  final tx = factory.createCall(
    sender: sender,
    nonce: nonce,
    endpointName: 'collectionSoup',
    arguments: <dynamic>[
      aList,
      aArr3,
      aOpt,
      aOptional,
      <dynamic>[aTuple.$1, aTuple.$2],
      aVariadic,
      <dynamic>[aMulti.$1, aMulti.$2],
      aNestedList,
      aListStruct,
    ],
    gasLimit: const GasLimit(600000000),
    value: value,
  );

  final gasLimit = await simulateGas(tx, networkProvider);

  return tx.copyWith(newGasLimit: gasLimit);
}
