// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by abidock_mvx code generator

import 'dart:typed_data';

import 'package:abidock_mvx/abidock_mvx.dart';

/// Calls primitiveSoup endpoint.
///
/// #### Parameters:
/// - `aU8`: u8
/// - `aI32`: i32
/// - `aBiguint`: BigUint
/// - `aBigint`: BigInt
/// - `aBool`: bool
/// - `aBytes`: bytes
/// - `aString`: String
/// - `aAddr`: Address
/// - `aTok`: TokenIdentifier
/// - `aEgesdt`: EgldOrEsdtTokenIdentifier
/// - `aH256`: H256
/// - `aCode`: CodeMetadata
///
/// #### Throws:
/// - [NetworkException] if network request fails
/// - [EndpointNotFoundException] if endpoint not found in ABI
/// - [ArgumentEncodingException] if ABI encoding fails
Future<Transaction> primitiveSoup(
  SmartContractController controller,
  IAccount sender,
  Nonce nonce,
  int aU8,
  int aI32,
  BigInt aBiguint,
  BigInt aBigint,
  bool aBool,
  Uint8List aBytes,
  String aString,
  Address aAddr,
  TokenIdentifier aTok,
  EgldOrEsdtTokenIdentifier aEgesdt,
  Uint8List aH256,
  List<int> aCode, {
  Address? relayer,
  Address? guardian,
  Balance? value,
}) async {
  final factory = SmartContractCallFactory(
    contractAddress: controller.contractAddress,
    abi: controller.abi,
    chainId: controller.networkProvider.chainId,
  );
  final probeTx = factory.createCall(
    sender: sender.address,
    nonce: nonce,
    endpointName: 'primitiveSoup',
    arguments: <dynamic>[
      aU8,
      aI32,
      aBiguint,
      aBigint,
      aBool,
      aBytes,
      aString,
      aAddr.bech32,
      aTok.value,
      aEgesdt.value,
      aH256,
      aCode,
    ],
    gasLimit: const GasLimit(600000000),
    value: value,
  );
  final gasLimit = await simulateGas(probeTx, controller.networkProvider);

  return controller.call(
    account: sender,
    nonce: nonce,
    endpointName: 'primitiveSoup',
    arguments: <dynamic>[
      aU8,
      aI32,
      aBiguint,
      aBigint,
      aBool,
      aBytes,
      aString,
      aAddr.bech32,
      aTok.value,
      aEgesdt.value,
      aH256,
      aCode,
    ],
    value: value,
    options: BaseControllerInput(
      gasLimit: gasLimit,
      relayer: relayer,
      guardian: guardian,
    ),
  );
}

/// Builds an unsigned transaction for primitiveSoup endpoint.
/// #### Parameters:
/// - `aU8`: u8
/// - `aI32`: i32
/// - `aBiguint`: BigUint
/// - `aBigint`: BigInt
/// - `aBool`: bool
/// - `aBytes`: bytes
/// - `aString`: String
/// - `aAddr`: Address
/// - `aTok`: TokenIdentifier
/// - `aEgesdt`: EgldOrEsdtTokenIdentifier
/// - `aH256`: H256
/// - `aCode`: CodeMetadata
///
/// #### Returns:
/// Future<[Transaction]> - Unsigned transaction with auto-estimated gas
///
/// #### Example:
/// ```dart
/// // Build unsigned transactions for batch signing
/// final tx1 = await primitiveSoupUnsigned(factory, provider, sender, nonce1, ...);
/// final tx2 = await anotherUnsigned(factory2, provider, sender, nonce2, ...);
///
/// // Sign batch
/// final sigs = await account.signTransactions([tx1, tx2]);
///
/// // Apply signatures and send
/// final signed1 = tx1.copyWith(newSignature: Signature.fromUint8List(sigs[0]));
/// final signed2 = tx2.copyWith(newSignature: Signature.fromUint8List(sigs[1]));
/// await provider.sendTransactions([signed1, signed2]);
/// ```
Future<Transaction> primitiveSoupUnsigned(
  SmartContractCallFactory factory,
  NetworkProvider networkProvider,
  Address sender,
  Nonce nonce,
  int aU8,
  int aI32,
  BigInt aBiguint,
  BigInt aBigint,
  bool aBool,
  Uint8List aBytes,
  String aString,
  Address aAddr,
  TokenIdentifier aTok,
  EgldOrEsdtTokenIdentifier aEgesdt,
  Uint8List aH256,
  List<int> aCode, {
  Balance? value,
}) async {
  final tx = factory.createCall(
    sender: sender,
    nonce: nonce,
    endpointName: 'primitiveSoup',
    arguments: <dynamic>[
      aU8,
      aI32,
      aBiguint,
      aBigint,
      aBool,
      aBytes,
      aString,
      aAddr.bech32,
      aTok.value,
      aEgesdt.value,
      aH256,
      aCode,
    ],
    gasLimit: const GasLimit(600000000),
    value: value,
  );

  final gasLimit = await simulateGas(tx, networkProvider);

  return tx.copyWith(newGasLimit: gasLimit);
}
