// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by abidock_mvx code generator

import 'package:abidock_mvx/abidock_mvx.dart';

/// Calls weirdParams endpoint.
///
/// #### Parameters:
/// - `valueParam`: u64
/// - `senderParam`: Address
/// - `classValue`: u32
/// - `newValue`: BigUint
/// - `field42numeric`: u32
/// - `controllerParam`: u32
/// - `factoryValue`: u32
///
/// #### Throws:
/// - [NetworkException] if network request fails
/// - [EndpointNotFoundException] if endpoint not found in ABI
/// - [ArgumentEncodingException] if ABI encoding fails
Future<Transaction> weirdParams(
  SmartContractController controller,
  IAccount sender,
  Nonce nonce,
  BigInt valueParam,
  Address senderParam,
  int classValue,
  BigInt newValue,
  int field42numeric,
  int controllerParam,
  int factoryValue, {
  Address? relayer,
  Address? guardian,
  Balance? value,
}) async {
  final factory = SmartContractCallFactory(
    contractAddress: controller.contractAddress,
    abi: controller.abi,
    chainId: controller.networkProvider.chainId,
  );
  final probeTx = factory.createCall(
    sender: sender.address,
    nonce: nonce,
    endpointName: 'weirdParams',
    arguments: <dynamic>[
      valueParam,
      senderParam.bech32,
      classValue,
      newValue,
      field42numeric,
      controllerParam,
      factoryValue,
    ],
    gasLimit: const GasLimit(600000000),
    value: value,
  );
  final gasLimit = await simulateGas(probeTx, controller.networkProvider);

  return controller.call(
    account: sender,
    nonce: nonce,
    endpointName: 'weirdParams',
    arguments: <dynamic>[
      valueParam,
      senderParam.bech32,
      classValue,
      newValue,
      field42numeric,
      controllerParam,
      factoryValue,
    ],
    value: value,
    options: BaseControllerInput(
      gasLimit: gasLimit,
      relayer: relayer,
      guardian: guardian,
    ),
  );
}

/// Builds an unsigned transaction for weirdParams endpoint.
/// #### Parameters:
/// - `valueParam`: u64
/// - `senderParam`: Address
/// - `classValue`: u32
/// - `newValue`: BigUint
/// - `field42numeric`: u32
/// - `controllerParam`: u32
/// - `factoryValue`: u32
///
/// #### Returns:
/// Future<[Transaction]> - Unsigned transaction with auto-estimated gas
///
/// #### Example:
/// ```dart
/// // Build unsigned transactions for batch signing
/// final tx1 = await weirdParamsUnsigned(factory, provider, sender, nonce1, ...);
/// final tx2 = await anotherUnsigned(factory2, provider, sender, nonce2, ...);
///
/// // Sign batch
/// final sigs = await account.signTransactions([tx1, tx2]);
///
/// // Apply signatures and send
/// final signed1 = tx1.copyWith(newSignature: Signature.fromUint8List(sigs[0]));
/// final signed2 = tx2.copyWith(newSignature: Signature.fromUint8List(sigs[1]));
/// await provider.sendTransactions([signed1, signed2]);
/// ```
Future<Transaction> weirdParamsUnsigned(
  SmartContractCallFactory factory,
  NetworkProvider networkProvider,
  Address sender,
  Nonce nonce,
  BigInt valueParam,
  Address senderParam,
  int classValue,
  BigInt newValue,
  int field42numeric,
  int controllerParam,
  int factoryValue, {
  Balance? value,
}) async {
  final tx = factory.createCall(
    sender: sender,
    nonce: nonce,
    endpointName: 'weirdParams',
    arguments: <dynamic>[
      valueParam,
      senderParam.bech32,
      classValue,
      newValue,
      field42numeric,
      controllerParam,
      factoryValue,
    ],
    gasLimit: const GasLimit(600000000),
    value: value,
  );

  final gasLimit = await simulateGas(tx, networkProvider);

  return tx.copyWith(newGasLimit: gasLimit);
}
