// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by abidock_mvx code generator

import 'dart:async';

import 'package:abidock_mvx/abidock_mvx.dart';

import '../../models/marker_only_event.dart';

/// Real-time WebSocket stream for marker_only_event events.
///
final class MarkerOnlyEventWebSocketStream {
  MarkerOnlyEventWebSocketStream({
    required SmartContractController controller,
    required String websocketUrl,
    Map<String, String>? headers,
    bool autoReconnect = true,
    Duration reconnectDelay = const Duration(seconds: 1),
    Duration connectionTimeout = const Duration(seconds: 5),
    Duration pingInterval = const Duration(seconds: 10),
  }) : _controller = controller {
    _config = WebSocketEventStreamConfig.byIdentifiers(
      websocketUrl: websocketUrl,
      identifiers: ['marker_only_event'],
      contractAddress: _controller.contractAddress,
      abi: _controller.abi,
      autoReconnect: autoReconnect,
      reconnectDelay: reconnectDelay,
      connectionTimeout: connectionTimeout,
      pingInterval: pingInterval,
      logger: _controller.logger,
    );

    _stream = WebSocketEventStream(_config);
  }

  final SmartContractController _controller;
  late final WebSocketEventStreamConfig _config;
  late final WebSocketEventStream _stream;

  /// Stream of typed MarkerOnlyEvent events filtered server-side.
  /// Converts WebSocket payloads into strongly typed objects.
  Stream<MarkerOnlyEvent> get events =>
      EventConverter.filterByIdentifier<MarkerOnlyEvent>(
        _stream.events,
        'marker_only_event',
        (parsed) => EventConverter.convertEvent<MarkerOnlyEvent>(
          parsed,
          MarkerOnlyEvent.fromAbi,
          MarkerOnlyEvent.type,
        ),
      );

  Stream<WebSocketStatusChange> get statusChanges => _stream.statusChanges;

  Stream<WebSocketEventError> get errors => _stream.errors;

  Future<void> connect() => _stream.connect();

  Future<void> disconnect() => _stream.disconnect();

  Future<void> dispose() => _stream.dispose();

  WebSocketStatus get status => _stream.status;

  void pause() => _stream.pause();

  void resume() => _stream.resume();
}
