// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by abidock_mvx code generator

import 'dart:async';
import 'dart:typed_data';

import 'package:abidock_mvx/abidock_mvx.dart';

import 'abi.dart';
import 'calls/byte_ops.dart' as byte_ops_call;
import 'calls/counted_var.dart' as counted_var_call;
import 'calls/egld_only.dart' as egld_only_call;
import 'calls/no_op.dart' as no_op_call;
import 'calls/specific_token.dart' as specific_token_call;
import 'calls/var_of_tuple.dart' as var_of_tuple_call;
import 'events/multi_event_websocket_stream.dart'
    as multi_event_websocket_stream;
import 'events/polling_events/marker.dart' as marker_polling_stream;
import 'events/websocket_events/marker.dart' as marker_websocket_stream;
import 'queries/multi_result_outputs.dart' as multi_result_outputs_query;
import 'queries/nested_option.dart' as nested_option_query;
import 'queries/return_list_of_list.dart' as return_list_of_list_query;

/// Smart contract controller.
///
/// #### Example
/// ```dart
/// final logger = ConsoleLogger(
///   minLevel: LogLevel.debug,
///   includeTimestamp: true,
///   prettyPrintContext: true,
///   showBorders: true,
///   useColors: true,
/// );
/// final controller = EdgeController(
///   contractAddress: 'erd1...',
///   networkProvider: provider,
///   logger: logger,
/// );
/// ```
class EdgeController {
  final SmartContractController _controller;

  /// Logger surface for this controller.
  ///
  /// Typed as the abstract [Logger] interface so any subtype passed
  /// to [SmartContractController] flows through unchanged.
  final Logger logger;

  /// Creates controller with contract address.
  EdgeController({
    required dynamic contractAddress,
    required NetworkProvider networkProvider,
    Logger? logger,
  }) : logger =
           logger ??
           ConsoleLogger(
             minLevel: LogLevel.debug,
             includeTimestamp: true,
             prettyPrintContext: true,
             showBorders: true,
             useColors: true,
           ),
       _controller = SmartContractController(
         abi: abi,
         contractAddress: contractAddress is String
             ? SmartContractAddress.fromBech32(contractAddress)
             : contractAddress as Address,
         networkProvider: networkProvider,
         logger:
             logger ??
             ConsoleLogger(
               minLevel: LogLevel.debug,
               includeTimestamp: true,
               prettyPrintContext: true,
               showBorders: true,
               useColors: true,
             ),
       );

  EdgeController.withController(this._controller)
    : logger = _controller.logger ?? ConsoleLogger(minLevel: LogLevel.debug);

  SmartContractController get controller => _controller;

  /// Network provider for queries and transactions.
  NetworkProvider get networkProvider => _controller.networkProvider;

  /// Factory for creating unsigned transactions.
  SmartContractCallFactory get factory => SmartContractCallFactory(
    contractAddress: _controller.contractAddress,
    abi: _controller.abi,
    chainId: _controller.networkProvider.chainId,
    logger: _controller.logger,
  );

  Future<List<BigInt>?> nestedOption(int? x) =>
      nested_option_query.nestedOption(_controller, x);

  Future<(BigInt, BigInt, BigInt)> multiResultOutputs() =>
      multi_result_outputs_query.multiResultOutputs(_controller);

  Future<List<List<BigInt>>> returnListOfList() =>
      return_list_of_list_query.returnListOfList(_controller);

  Future<Transaction> noOp(
    IAccount sender,
    Nonce nonce, {
    Address? relayer,
    Address? guardian,
    Balance? value,
  }) => no_op_call.noOp(
    _controller,
    sender,
    nonce,
    relayer: relayer,
    guardian: guardian,
    value: value,
  );

  Future<Transaction> varOfTuple(
    IAccount sender,
    Nonce nonce,
    List<(int, Address)> items, {
    Address? relayer,
    Address? guardian,
    Balance? value,
  }) => var_of_tuple_call.varOfTuple(
    _controller,
    sender,
    nonce,
    items,
    relayer: relayer,
    guardian: guardian,
    value: value,
  );

  Future<Transaction> countedVar(
    IAccount sender,
    Nonce nonce,
    List<TokenIdentifier> ids, {
    Address? relayer,
    Address? guardian,
    Balance? value,
  }) => counted_var_call.countedVar(
    _controller,
    sender,
    nonce,
    ids,
    relayer: relayer,
    guardian: guardian,
    value: value,
  );

  Future<Transaction> egldOnly(
    IAccount sender,
    Nonce nonce, {
    List<TokenTransferValue> tokenTransfers = const <TokenTransferValue>[],
    Address? relayer,
    Address? guardian,
    Balance? value,
  }) => egld_only_call.egldOnly(
    _controller,
    sender,
    nonce,
    tokenTransfers: tokenTransfers,
    relayer: relayer,
    guardian: guardian,
    value: value,
  );

  Future<Transaction> specificToken(
    IAccount sender,
    Nonce nonce, {
    List<TokenTransferValue> tokenTransfers = const <TokenTransferValue>[],
    Address? relayer,
    Address? guardian,
    Balance? value,
  }) => specific_token_call.specificToken(
    _controller,
    sender,
    nonce,
    tokenTransfers: tokenTransfers,
    relayer: relayer,
    guardian: guardian,
    value: value,
  );

  Future<Transaction> byteOps(
    IAccount sender,
    Nonce nonce,
    Uint8List hash,
    Uint8List blob, {
    Address? relayer,
    Address? guardian,
    Balance? value,
  }) => byte_ops_call.byteOps(
    _controller,
    sender,
    nonce,
    hash,
    blob,
    relayer: relayer,
    guardian: guardian,
    value: value,
  );

  Future<Transaction> noOpUnsigned(
    Address sender,
    Nonce nonce, {
    Balance? value,
  }) => no_op_call.noOpUnsigned(
    factory,
    networkProvider,
    sender,
    nonce,
    value: value,
  );

  Future<Transaction> varOfTupleUnsigned(
    Address sender,
    Nonce nonce,
    List<(int, Address)> items, {
    Balance? value,
  }) => var_of_tuple_call.varOfTupleUnsigned(
    factory,
    networkProvider,
    sender,
    nonce,
    items,
    value: value,
  );

  Future<Transaction> countedVarUnsigned(
    Address sender,
    Nonce nonce,
    List<TokenIdentifier> ids, {
    Balance? value,
  }) => counted_var_call.countedVarUnsigned(
    factory,
    networkProvider,
    sender,
    nonce,
    ids,
    value: value,
  );

  Future<Transaction> egldOnlyUnsigned(
    Address sender,
    Nonce nonce, {
    List<TokenTransferValue> tokenTransfers = const <TokenTransferValue>[],
    Balance? value,
  }) => egld_only_call.egldOnlyUnsigned(
    factory,
    networkProvider,
    sender,
    nonce,
    tokenTransfers: tokenTransfers,
    value: value,
  );

  Future<Transaction> specificTokenUnsigned(
    Address sender,
    Nonce nonce, {
    List<TokenTransferValue> tokenTransfers = const <TokenTransferValue>[],
    Balance? value,
  }) => specific_token_call.specificTokenUnsigned(
    factory,
    networkProvider,
    sender,
    nonce,
    tokenTransfers: tokenTransfers,
    value: value,
  );

  Future<Transaction> byteOpsUnsigned(
    Address sender,
    Nonce nonce,
    Uint8List hash,
    Uint8List blob, {
    Balance? value,
  }) => byte_ops_call.byteOpsUnsigned(
    factory,
    networkProvider,
    sender,
    nonce,
    hash,
    blob,
    value: value,
  );

  late final EdgeEvents events = EdgeEvents(_controller);
}

/// Event streaming accessor
class EdgeEvents {
  const EdgeEvents(this._controller);

  final SmartContractController _controller;

  /// Create a unified WebSocket stream for multiple events.
  ///
  /// More efficient than individual streams - uses single WebSocket connection.
  ///
  /// Example:
  /// ```dart
  /// final stream = controller.events.websocketStream(
  ///   websocketUrl: 'wss://kepler-api.projectx.mx/mainnet/events',
  ///   headers: {'Api-Key': 'your-key'},
  /// );
  /// await stream.connect();
  ///
  /// // Listen to specific events
  /// stream.marker.listen((event) => print(event));
  ///
  /// // Or listen to all events
  /// stream.all.listen((event) { ... });
  /// ```
  multi_event_websocket_stream.MultiEventWebSocketStream websocketStream({
    required String websocketUrl,
    Map<String, String> headers = const {},
    bool autoReconnect = true,
    Duration reconnectDelay = const Duration(seconds: 1),
    Duration connectionTimeout = const Duration(seconds: 5),
    Duration pingInterval = const Duration(seconds: 10),
  }) {
    return multi_event_websocket_stream.MultiEventWebSocketStream(
      controller: _controller,
      websocketUrl: websocketUrl,
      headers: headers,
      autoReconnect: autoReconnect,
      reconnectDelay: reconnectDelay,
      connectionTimeout: connectionTimeout,
      pingInterval: pingInterval,
    );
  }

  marker_polling_stream.MarkerPollingStream markerPolling() =>
      marker_polling_stream.MarkerPollingStream(_controller);

  marker_websocket_stream.MarkerWebSocketStream markerWebSocket({
    required String websocketUrl,
    Map<String, String> headers = const {},
    bool autoReconnect = true,
    Duration reconnectDelay = const Duration(seconds: 5),
    Duration connectionTimeout = const Duration(seconds: 15),
    Duration pingInterval = const Duration(seconds: 30),
  }) {
    return marker_websocket_stream.MarkerWebSocketStream(
      controller: _controller,
      websocketUrl: websocketUrl,
      headers: headers,
      autoReconnect: autoReconnect,
      reconnectDelay: reconnectDelay,
      connectionTimeout: connectionTimeout,
      pingInterval: pingInterval,
    );
  }
}
