// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by abidock_mvx code generator

import 'package:abidock_mvx/abidock_mvx.dart';

/// Transfers ESDT fungible tokens.
///
/// Creates and signs a transaction for transferring ESDT tokens.
/// Supports any fungible ESDT token with specified amount.
///
/// Example:
/// ```dart
/// final provider = GatewayProvider(
///   gatewayUrl: 'https://gateway.multiversx.com',
/// );
/// final tx = await esdt(
///   provider,
///   sender: alice,
///   nonce: nonce,
///   receiver: bobAddress,
///   tokenId: 'MYTOKEN-abc123',
///   amount: BigInt.from(1000),
/// );
/// await provider.sendTransaction(tx);
/// ```
Future<Transaction> esdt(
  NetworkProvider provider,
  IAccount sender,
  Nonce nonce,
  Address receiver,
  String tokenId,
  BigInt amount, {
  Address? relayer,
  Address? guardian,
  GasLimit? gasLimit,
}) async {
  final transfersCtrl = TransfersController(chainId: provider.chainId);

  final tx = await transfersCtrl.createTransactionForTokenTransfer(
    sender,
    nonce,
    TokenTransferInput(
      receiver: receiver,
      transfers: [
        TokenTransfer.fungible(tokenIdentifier: tokenId, amount: amount),
      ],
    ),
    baseOptions: gasLimit != null || relayer != null || guardian != null
        ? BaseControllerInput(
            gasLimit: gasLimit,
            relayer: relayer,
            guardian: guardian,
          )
        : const BaseControllerInput(),
  );

  return tx;
}
