// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by abidock_mvx code generator

import 'dart:typed_data';

import 'package:abidock_mvx/abidock_mvx.dart';

/// Builds an unsigned deploy transaction.
///
/// Typed wrapper over [SmartContractTransactionsFactory.createTransactionForDeploy].
///
/// #### Constructor parameters:
/// - `owner`: Address
/// - `fee`: u64
Transaction deploy(
  NetworkProvider networkProvider,
  Address sender,
  Nonce nonce,
  Uint8List bytecode,
  GasLimit gasLimit,
  Address owner,
  BigInt fee, {
  Uint8List? codeMetadata,
  String vmType = '0500',
}) {
  final factory = SmartContractTransactionsFactory(
    SmartContractTransactionsConfig(chainId: networkProvider.chainId),
  );

  final typedArgs = <TypedValue>[
    AddressType.type.createValue(owner.bech32),
    U64Type.type.createValue(fee),
  ];
  final argBytes = ArgSerializer().valuesToBuffers(typedArgs);

  return factory.createTransactionForDeploy(
    sender: sender,
    bytecode: bytecode,
    gasLimit: gasLimit,
    codeMetadata: codeMetadata,
    vmType: vmType,
    arguments: argBytes,
    nonce: nonce,
  );
}
