// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by abidock_mvx code generator

import 'dart:typed_data';

import 'package:abidock_mvx/abidock_mvx.dart';

/// Builds an unsigned upgrade transaction.
///
/// Typed wrapper over [SmartContractTransactionsFactory.createTransactionForUpgrade].
///
/// #### Constructor parameters:
/// - `newFee`: u64
Transaction upgrade(
  NetworkProvider networkProvider,
  Address sender,
  Nonce nonce,
  Uint8List bytecode,
  GasLimit gasLimit,
  Address contract,
  BigInt newFee, {
  Uint8List? codeMetadata,
}) {
  final factory = SmartContractTransactionsFactory(
    SmartContractTransactionsConfig(chainId: networkProvider.chainId),
  );

  final typedArgs = <TypedValue>[U64Type.type.createValue(newFee)];
  final argBytes = ArgSerializer().valuesToBuffers(typedArgs);

  return factory.createTransactionForUpgrade(
    sender: sender,
    contract: contract,
    bytecode: bytecode,
    gasLimit: gasLimit,
    codeMetadata: codeMetadata,
    arguments: argBytes,
    nonce: nonce,
  );
}
