// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by abidock_mvx code generator

import 'dart:async';

import 'package:abidock_mvx/abidock_mvx.dart';

import '../models/complex_event.dart';
import '../models/marker_only_event.dart';
import '../models/transfer_event.dart';

/// HTTP polling stream that fans out every event.
/// Runs one polling loop and exposes typed getters.
final class MultiEventPollingStream {
  MultiEventPollingStream({
    required this.controller,
    Duration pollingInterval = const Duration(seconds: 10),
    String? startFrom,
  }) {
    _baseStream = controller
        .streamAllEvents(pollingInterval: pollingInterval, startFrom: startFrom)
        .asBroadcastStream(onCancel: (sub) => sub.cancel());
  }

  final SmartContractController controller;
  late final Stream<ParsedEvent> _baseStream;

  /// Stream of transfer_event events.
  Stream<TransferEvent> get transferEvent => _baseStream
      .where((event) => event.definition.identifier == 'transfer_event')
      .map((parsedEvent) {
        final decoded = EventConverter.convertEvent<TransferEvent>(
          parsedEvent,
          TransferEvent.fromAbi,
          TransferEvent.type,
        );
        if (decoded == null) {
          throw StateError('Failed to decode transfer_event event');
        }
        return decoded;
      });

  /// Stream of complex_event events.
  Stream<ComplexEvent> get complexEvent => _baseStream
      .where((event) => event.definition.identifier == 'complex_event')
      .map((parsedEvent) {
        final decoded = EventConverter.convertEvent<ComplexEvent>(
          parsedEvent,
          ComplexEvent.fromAbi,
          ComplexEvent.type,
        );
        if (decoded == null) {
          throw StateError('Failed to decode complex_event event');
        }
        return decoded;
      });

  /// Stream of marker_only_event events.
  Stream<MarkerOnlyEvent> get markerOnlyEvent => _baseStream
      .where((event) => event.definition.identifier == 'marker_only_event')
      .map((parsedEvent) {
        final decoded = EventConverter.convertEvent<MarkerOnlyEvent>(
          parsedEvent,
          MarkerOnlyEvent.fromAbi,
          MarkerOnlyEvent.type,
        );
        if (decoded == null) {
          throw StateError('Failed to decode marker_only_event event');
        }
        return decoded;
      });

  /// Stream of all event types as dynamic objects.
  ///
  /// Use type checking to handle different event types:
  /// ```dart
  /// stream.all.listen((event) {
  ///   if (event is TransferEvent) {
  ///     // Handle transfer_event
  ///   }
  ///   else if (event is ComplexEvent) {
  ///     // Handle complex_event
  ///   }
  ///   else if (event is MarkerOnlyEvent) {
  ///     // Handle marker_only_event
  ///   }
  /// });
  /// ```
  Stream<dynamic> get all {
    return _baseStream
        .asyncMap((parsedEvent) async {
          final identifier = parsedEvent.definition.identifier;
          switch (identifier) {
            case 'transfer_event':
              return EventConverter.convertEvent<TransferEvent>(
                parsedEvent,
                TransferEvent.fromAbi,
                TransferEvent.type,
              );
            case 'complex_event':
              return EventConverter.convertEvent<ComplexEvent>(
                parsedEvent,
                ComplexEvent.fromAbi,
                ComplexEvent.type,
              );
            case 'marker_only_event':
              return EventConverter.convertEvent<MarkerOnlyEvent>(
                parsedEvent,
                MarkerOnlyEvent.fromAbi,
                MarkerOnlyEvent.type,
              );
            default:
              return null;
          }
        })
        .where((event) => event != null)
        .cast<dynamic>();
  }

  /// Stream filtered to only specified event types.
  ///
  /// #### Example
  /// ```dart
  /// stream.only([TransferEventEvent, ComplexEventEvent]).listen((event) {
  ///   // Only transfer_event and complex_event events
  /// });
  /// ```
  Stream<dynamic> only(List<Type> types) {
    return all.where((event) => types.contains(event.runtimeType));
  }
}
