// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by abidock_mvx code generator

import 'dart:async';

import 'package:abidock_mvx/abidock_mvx.dart';

import '../models/complex_event.dart';
import '../models/marker_only_event.dart';
import '../models/transfer_event.dart';

/// Combined WebSocket stream that fans out every event.
/// Use typed getters, `all`, or `only` to consume events.
final class MultiEventWebSocketStream {
  MultiEventWebSocketStream({
    required SmartContractController controller,
    required String websocketUrl,
    Map<String, String> headers = const {},
    bool autoReconnect = true,
    Duration reconnectDelay = const Duration(seconds: 1),
    Duration connectionTimeout = const Duration(seconds: 5),
    Duration pingInterval = const Duration(seconds: 10),
  }) : _controller = controller {
    _config = WebSocketEventStreamConfig.byIdentifiers(
      websocketUrl: websocketUrl,
      identifiers: ['transfer_event', 'complex_event', 'marker_only_event'],
      contractAddress: _controller.contractAddress,
      abi: _controller.abi,
      headers: headers,
      logger: _controller.logger,
      autoReconnect: autoReconnect,
      reconnectDelay: reconnectDelay,
      connectionTimeout: connectionTimeout,
      pingInterval: pingInterval,
    );

    _stream = WebSocketEventStream(_config);
  }

  final SmartContractController _controller;
  late final WebSocketEventStreamConfig _config;
  late final WebSocketEventStream _stream;

  /// Stream of transfer_event events.
  Stream<TransferEvent> get transferEvent =>
      EventConverter.filterByIdentifier<TransferEvent>(
        _stream.events,
        'transfer_event',
        (parsed) => EventConverter.convertEvent<TransferEvent>(
          parsed,
          TransferEvent.fromAbi,
          TransferEvent.type,
        ),
      );

  /// Stream of complex_event events.
  Stream<ComplexEvent> get complexEvent =>
      EventConverter.filterByIdentifier<ComplexEvent>(
        _stream.events,
        'complex_event',
        (parsed) => EventConverter.convertEvent<ComplexEvent>(
          parsed,
          ComplexEvent.fromAbi,
          ComplexEvent.type,
        ),
      );

  /// Stream of marker_only_event events.
  Stream<MarkerOnlyEvent> get markerOnlyEvent =>
      EventConverter.filterByIdentifier<MarkerOnlyEvent>(
        _stream.events,
        'marker_only_event',
        (parsed) => EventConverter.convertEvent<MarkerOnlyEvent>(
          parsed,
          MarkerOnlyEvent.fromAbi,
          MarkerOnlyEvent.type,
        ),
      );

  /// Stream of all events (any type).
  ///
  /// Use type checks to handle different events:
  /// ```dart
  /// stream.all.listen((event) {
  ///   if (event is TransferEventEvent) { ... }
  /// });
  /// ```
  Stream<dynamic> get all => _stream.events
      .where((r) => r.parsedEvent != null)
      .map((r) {
        final identifier = r.parsedEvent!.definition.identifier;
        switch (identifier) {
          case 'transfer_event':
            return EventConverter.convertEvent<TransferEvent>(
              r.parsedEvent!,
              TransferEvent.fromAbi,
              TransferEvent.type,
            );
          case 'complex_event':
            return EventConverter.convertEvent<ComplexEvent>(
              r.parsedEvent!,
              ComplexEvent.fromAbi,
              ComplexEvent.type,
            );
          case 'marker_only_event':
            return EventConverter.convertEvent<MarkerOnlyEvent>(
              r.parsedEvent!,
              MarkerOnlyEvent.fromAbi,
              MarkerOnlyEvent.type,
            );
          default:
            return null;
        }
      })
      .where((event) => event != null)
      .cast<dynamic>();

  /// Filter to only specified event types.
  ///
  /// Example:
  /// ```dart
  /// stream.only([TransferEventEvent, ComplexEventEvent]).listen((event) {
  ///   // Only receive these event types
  /// });
  /// ```
  Stream<dynamic> only(List<Type> eventTypes) {
    return all.where((event) => eventTypes.contains(event.runtimeType));
  }

  /// Stream of connection status changes.
  Stream<WebSocketStatusChange> get statusChanges => _stream.statusChanges;

  /// Stream of WebSocket errors.
  Stream<WebSocketEventError> get errors => _stream.errors;

  /// Connects to WebSocket server.
  Future<void> connect() => _stream.connect();

  /// Disconnects from WebSocket server.
  Future<void> disconnect() => _stream.disconnect();

  /// Dispose resources.
  Future<void> dispose() => _stream.dispose();

  /// Current connection status.
  WebSocketStatus get status => _stream.status;

  /// Pause event streaming.
  void pause() => _stream.pause();

  /// Resume event streaming.
  void resume() => _stream.resume();
}
