// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by abidock_mvx code generator

import 'package:abidock_mvx/abidock_mvx.dart';

/// RemoveLiquidityEvent model.
class RemoveLiquidityEvent {
  const RemoveLiquidityEvent({
    required this.caller,
    required this.firstTokenId,
    required this.firstTokenAmount,
    required this.secondTokenId,
    required this.secondTokenAmount,
    required this.lpTokenId,
    required this.lpTokenAmount,
    required this.lpSupply,
    required this.firstTokenReserves,
    required this.secondTokenReserves,
    required this.block,
    required this.epoch,
    required this.timestamp,
  });

  final Address caller;
  final TokenIdentifier firstTokenId;
  final BigInt firstTokenAmount;
  final TokenIdentifier secondTokenId;
  final BigInt secondTokenAmount;
  final TokenIdentifier lpTokenId;
  final BigInt lpTokenAmount;
  final BigInt lpSupply;
  final BigInt firstTokenReserves;
  final BigInt secondTokenReserves;
  final BigInt block;
  final BigInt epoch;
  final BigInt timestamp;

  static final StructType type = StructType(
    name: 'RemoveLiquidityEvent',
    fieldDefinitions: [
      FieldDefinition(name: 'caller', type: AddressType.type),
      FieldDefinition(name: 'first_token_id', type: TokenIdentifierType.type),
      FieldDefinition(name: 'first_token_amount', type: BigUIntType.type),
      FieldDefinition(name: 'second_token_id', type: TokenIdentifierType.type),
      FieldDefinition(name: 'second_token_amount', type: BigUIntType.type),
      FieldDefinition(name: 'lp_token_id', type: TokenIdentifierType.type),
      FieldDefinition(name: 'lp_token_amount', type: BigUIntType.type),
      FieldDefinition(name: 'lp_supply', type: BigUIntType.type),
      FieldDefinition(name: 'first_token_reserves', type: BigUIntType.type),
      FieldDefinition(name: 'second_token_reserves', type: BigUIntType.type),
      FieldDefinition(name: 'block', type: U64Type.type),
      FieldDefinition(name: 'epoch', type: U64Type.type),
      FieldDefinition(name: 'timestamp', type: U64Type.type),
    ],
  );

  factory RemoveLiquidityEvent.fromAbi(TypedValue value) {
    final struct = value as StructValue;
    return RemoveLiquidityEvent(
      caller: Address.fromBech32(
        struct.getFieldValue('caller').nativeValue as String,
      ),
      firstTokenId: TokenIdentifier(
        struct.getFieldValue('first_token_id').nativeValue as String,
      ),
      firstTokenAmount:
          struct.getFieldValue('first_token_amount').nativeValue as BigInt,
      secondTokenId: TokenIdentifier(
        struct.getFieldValue('second_token_id').nativeValue as String,
      ),
      secondTokenAmount:
          struct.getFieldValue('second_token_amount').nativeValue as BigInt,
      lpTokenId: TokenIdentifier(
        struct.getFieldValue('lp_token_id').nativeValue as String,
      ),
      lpTokenAmount:
          struct.getFieldValue('lp_token_amount').nativeValue as BigInt,
      lpSupply: struct.getFieldValue('lp_supply').nativeValue as BigInt,
      firstTokenReserves:
          struct.getFieldValue('first_token_reserves').nativeValue as BigInt,
      secondTokenReserves:
          struct.getFieldValue('second_token_reserves').nativeValue as BigInt,
      block: struct.getFieldValue('block').nativeValue as BigInt,
      epoch: struct.getFieldValue('epoch').nativeValue as BigInt,
      timestamp: struct.getFieldValue('timestamp').nativeValue as BigInt,
    );
  }

  TypedValue toAbi() {
    return type.createValue({
      'caller': caller.bech32,
      'first_token_id': firstTokenId.value,
      'first_token_amount': firstTokenAmount,
      'second_token_id': secondTokenId.value,
      'second_token_amount': secondTokenAmount,
      'lp_token_id': lpTokenId.value,
      'lp_token_amount': lpTokenAmount,
      'lp_supply': lpSupply,
      'first_token_reserves': firstTokenReserves,
      'second_token_reserves': secondTokenReserves,
      'block': block,
      'epoch': epoch,
      'timestamp': timestamp,
    });
  }

  Map<String, dynamic> toJson() {
    return {
      'caller': caller.bech32,
      'first_token_id': firstTokenId.value,
      'first_token_amount': firstTokenAmount.toString(),
      'second_token_id': secondTokenId.value,
      'second_token_amount': secondTokenAmount.toString(),
      'lp_token_id': lpTokenId.value,
      'lp_token_amount': lpTokenAmount.toString(),
      'lp_supply': lpSupply.toString(),
      'first_token_reserves': firstTokenReserves.toString(),
      'second_token_reserves': secondTokenReserves.toString(),
      'block': block.toString(),
      'epoch': epoch.toString(),
      'timestamp': timestamp.toString(),
    };
  }
}
