// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by abidock_mvx code generator

import 'package:abidock_mvx/abidock_mvx.dart';

import 'remove_liquidity_event.dart';

/// Event model for remove_liquidity.
final class RemoveLiquidityEventData {
  const RemoveLiquidityEventData({
    required this.firstToken,
    required this.secondToken,
    required this.caller,
    required this.epoch,
    required this.removeLiquidityEvent,
  });

  final TokenIdentifier firstToken;
  final TokenIdentifier secondToken;
  final Address caller;
  final BigInt epoch;
  final RemoveLiquidityEvent removeLiquidityEvent;

  /// ABI type definition.
  static final type = StructType(
    name: 'RemoveLiquidityEventData',
    fieldDefinitions: [
      FieldDefinition(name: 'first_token', type: TokenIdentifierType.type),
      FieldDefinition(name: 'second_token', type: TokenIdentifierType.type),
      FieldDefinition(name: 'caller', type: AddressType.type),
      FieldDefinition(name: 'epoch', type: U64Type.type),
      FieldDefinition(
        name: 'remove_liquidity_event',
        type: RemoveLiquidityEvent.type,
      ),
    ],
  );

  /// Creates an instance from ABI data.
  factory RemoveLiquidityEventData.fromAbi(TypedValue value) {
    final struct = value as StructValue;
    return RemoveLiquidityEventData(
      firstToken: TokenIdentifier(
        struct.getFieldValue('first_token').nativeValue as String,
      ),
      secondToken: TokenIdentifier(
        struct.getFieldValue('second_token').nativeValue as String,
      ),
      caller: Address.fromBech32(
        struct.getFieldValue('caller').nativeValue as String,
      ),
      epoch: struct.getFieldValue('epoch').nativeValue as BigInt,
      removeLiquidityEvent: RemoveLiquidityEvent.fromAbi(
        struct.getFieldValue('remove_liquidity_event'),
      ),
    );
  }

  /// Converts to JSON map.
  Map<String, dynamic> toJson() {
    return {
      'first_token': firstToken.value,
      'second_token': secondToken.value,
      'caller': caller.bech32,
      'epoch': epoch.toString(),
      'remove_liquidity_event': removeLiquidityEvent.toString(),
    };
  }

  @override
  String toString() =>
      'RemoveLiquidityEventData(firstToken: $firstToken, secondToken: $secondToken, caller: $caller, ...)';

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is RemoveLiquidityEventData &&
        other.firstToken == firstToken &&
        other.secondToken == secondToken &&
        other.caller == caller &&
        other.epoch == epoch &&
        other.removeLiquidityEvent == removeLiquidityEvent;
  }

  @override
  int get hashCode {
    return Object.hash(
      firstToken,
      secondToken,
      caller,
      epoch,
      removeLiquidityEvent,
    );
  }
}
