// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by abidock_mvx code generator

import 'package:abidock_mvx/abidock_mvx.dart';

/// SwapEvent model.
class SwapEvent {
  const SwapEvent({
    required this.caller,
    required this.tokenIdIn,
    required this.tokenAmountIn,
    required this.tokenIdOut,
    required this.tokenAmountOut,
    required this.feeAmount,
    required this.tokenInReserve,
    required this.tokenOutReserve,
    required this.block,
    required this.epoch,
    required this.timestamp,
  });

  final Address caller;
  final TokenIdentifier tokenIdIn;
  final BigInt tokenAmountIn;
  final TokenIdentifier tokenIdOut;
  final BigInt tokenAmountOut;
  final BigInt feeAmount;
  final BigInt tokenInReserve;
  final BigInt tokenOutReserve;
  final BigInt block;
  final BigInt epoch;
  final BigInt timestamp;

  static final StructType type = StructType(
    name: 'SwapEvent',
    fieldDefinitions: [
      FieldDefinition(name: 'caller', type: AddressType.type),
      FieldDefinition(name: 'token_id_in', type: TokenIdentifierType.type),
      FieldDefinition(name: 'token_amount_in', type: BigUIntType.type),
      FieldDefinition(name: 'token_id_out', type: TokenIdentifierType.type),
      FieldDefinition(name: 'token_amount_out', type: BigUIntType.type),
      FieldDefinition(name: 'fee_amount', type: BigUIntType.type),
      FieldDefinition(name: 'token_in_reserve', type: BigUIntType.type),
      FieldDefinition(name: 'token_out_reserve', type: BigUIntType.type),
      FieldDefinition(name: 'block', type: U64Type.type),
      FieldDefinition(name: 'epoch', type: U64Type.type),
      FieldDefinition(name: 'timestamp', type: U64Type.type),
    ],
  );

  factory SwapEvent.fromAbi(TypedValue value) {
    final struct = value as StructValue;
    return SwapEvent(
      caller: Address.fromBech32(
        struct.getFieldValue('caller').nativeValue as String,
      ),
      tokenIdIn: TokenIdentifier(
        struct.getFieldValue('token_id_in').nativeValue as String,
      ),
      tokenAmountIn:
          struct.getFieldValue('token_amount_in').nativeValue as BigInt,
      tokenIdOut: TokenIdentifier(
        struct.getFieldValue('token_id_out').nativeValue as String,
      ),
      tokenAmountOut:
          struct.getFieldValue('token_amount_out').nativeValue as BigInt,
      feeAmount: struct.getFieldValue('fee_amount').nativeValue as BigInt,
      tokenInReserve:
          struct.getFieldValue('token_in_reserve').nativeValue as BigInt,
      tokenOutReserve:
          struct.getFieldValue('token_out_reserve').nativeValue as BigInt,
      block: struct.getFieldValue('block').nativeValue as BigInt,
      epoch: struct.getFieldValue('epoch').nativeValue as BigInt,
      timestamp: struct.getFieldValue('timestamp').nativeValue as BigInt,
    );
  }

  TypedValue toAbi() {
    return type.createValue({
      'caller': caller.bech32,
      'token_id_in': tokenIdIn.value,
      'token_amount_in': tokenAmountIn,
      'token_id_out': tokenIdOut.value,
      'token_amount_out': tokenAmountOut,
      'fee_amount': feeAmount,
      'token_in_reserve': tokenInReserve,
      'token_out_reserve': tokenOutReserve,
      'block': block,
      'epoch': epoch,
      'timestamp': timestamp,
    });
  }

  Map<String, dynamic> toJson() {
    return {
      'caller': caller.bech32,
      'token_id_in': tokenIdIn.value,
      'token_amount_in': tokenAmountIn.toString(),
      'token_id_out': tokenIdOut.value,
      'token_amount_out': tokenAmountOut.toString(),
      'fee_amount': feeAmount.toString(),
      'token_in_reserve': tokenInReserve.toString(),
      'token_out_reserve': tokenOutReserve.toString(),
      'block': block.toString(),
      'epoch': epoch.toString(),
      'timestamp': timestamp.toString(),
    };
  }
}
