// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by abidock_mvx code generator

import 'package:abidock_mvx/abidock_mvx.dart';

import 'swap_no_fee_and_forward_event.dart';

/// Event model for swap_no_fee_and_forward.
final class SwapNoFeeAndForwardEventData {
  const SwapNoFeeAndForwardEventData({
    required this.tokenIdOut,
    required this.caller,
    required this.epoch,
    required this.swapNoFeeAndForwardEvent,
  });

  final TokenIdentifier tokenIdOut;
  final Address caller;
  final BigInt epoch;
  final SwapNoFeeAndForwardEvent swapNoFeeAndForwardEvent;

  /// ABI type definition.
  static final type = StructType(
    name: 'SwapNoFeeAndForwardEventData',
    fieldDefinitions: [
      FieldDefinition(name: 'token_id_out', type: TokenIdentifierType.type),
      FieldDefinition(name: 'caller', type: AddressType.type),
      FieldDefinition(name: 'epoch', type: U64Type.type),
      FieldDefinition(
        name: 'swap_no_fee_and_forward_event',
        type: SwapNoFeeAndForwardEvent.type,
      ),
    ],
  );

  /// Creates an instance from ABI data.
  factory SwapNoFeeAndForwardEventData.fromAbi(TypedValue value) {
    final struct = value as StructValue;
    return SwapNoFeeAndForwardEventData(
      tokenIdOut: TokenIdentifier(
        struct.getFieldValue('token_id_out').nativeValue as String,
      ),
      caller: Address.fromBech32(
        struct.getFieldValue('caller').nativeValue as String,
      ),
      epoch: struct.getFieldValue('epoch').nativeValue as BigInt,
      swapNoFeeAndForwardEvent: SwapNoFeeAndForwardEvent.fromAbi(
        struct.getFieldValue('swap_no_fee_and_forward_event'),
      ),
    );
  }

  /// Converts to JSON map.
  Map<String, dynamic> toJson() {
    return {
      'token_id_out': tokenIdOut.value,
      'caller': caller.bech32,
      'epoch': epoch.toString(),
      'swap_no_fee_and_forward_event': swapNoFeeAndForwardEvent.toString(),
    };
  }

  @override
  String toString() =>
      'SwapNoFeeAndForwardEventData(tokenIdOut: $tokenIdOut, caller: $caller, epoch: $epoch, ...)';

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is SwapNoFeeAndForwardEventData &&
        other.tokenIdOut == tokenIdOut &&
        other.caller == caller &&
        other.epoch == epoch &&
        other.swapNoFeeAndForwardEvent == swapNoFeeAndForwardEvent;
  }

  @override
  int get hashCode {
    return Object.hash(tokenIdOut, caller, epoch, swapNoFeeAndForwardEvent);
  }
}
