// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by abidock_mvx code generator

import 'package:abidock_mvx/abidock_mvx.dart';

/// TokenPair model.
class TokenPair {
  const TokenPair({required this.firstToken, required this.secondToken});

  final TokenIdentifier firstToken;
  final TokenIdentifier secondToken;

  static final StructType type = StructType(
    name: 'TokenPair',
    fieldDefinitions: [
      FieldDefinition(name: 'first_token', type: TokenIdentifierType.type),
      FieldDefinition(name: 'second_token', type: TokenIdentifierType.type),
    ],
  );

  factory TokenPair.fromAbi(TypedValue value) {
    final struct = value as StructValue;
    return TokenPair(
      firstToken: TokenIdentifier(
        struct.getFieldValue('first_token').nativeValue as String,
      ),
      secondToken: TokenIdentifier(
        struct.getFieldValue('second_token').nativeValue as String,
      ),
    );
  }

  TypedValue toAbi() {
    return type.createValue({
      'first_token': firstToken.value,
      'second_token': secondToken.value,
    });
  }

  Map<String, dynamic> toJson() {
    return {'first_token': firstToken.value, 'second_token': secondToken.value};
  }
}
