// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by abidock_mvx code generator

import 'dart:async';
import 'dart:typed_data';

import 'package:abidock_mvx/abidock_mvx.dart';

import 'abi.dart';
import 'calls/collection_soup.dart' as collection_soup_call;
import 'calls/empty_mutable.dart' as empty_mutable_call;
import 'calls/payable_op_any.dart' as payable_op_any_call;
import 'calls/payable_op_egld.dart' as payable_op_egld_call;
import 'calls/payable_op_specific.dart' as payable_op_specific_call;
import 'calls/primitive_soup.dart' as primitive_soup_call;
import 'calls/weird_params.dart' as weird_params_call;
import 'events/multi_event_polling_stream.dart' as multi_event_polling_stream;
import 'events/multi_event_websocket_stream.dart'
    as multi_event_websocket_stream;
import 'events/polling_events/complex_event.dart'
    as complex_event_polling_stream;
import 'events/polling_events/marker_only_event.dart'
    as marker_only_event_polling_stream;
import 'events/polling_events/transfer_event.dart'
    as transfer_event_polling_stream;
import 'events/websocket_events/complex_event.dart'
    as complex_event_websocket_stream;
import 'events/websocket_events/marker_only_event.dart'
    as marker_only_event_websocket_stream;
import 'events/websocket_events/transfer_event.dart'
    as transfer_event_websocket_stream;
import 'models/http_code.dart';
import 'models/status.dart';
import 'models/token_payment.dart';
import 'queries/query_nothing.dart' as query_nothing_query;
import 'queries/query_return_enum.dart' as query_return_enum_query;
import 'queries/query_return_explicit.dart' as query_return_explicit_query;
import 'queries/query_return_multi_tuple.dart'
    as query_return_multi_tuple_query;
import 'queries/query_return_struct.dart' as query_return_struct_query;

/// Smart contract controller.
///
/// #### Example
/// ```dart
/// final logger = ConsoleLogger(
///   minLevel: LogLevel.debug,
///   includeTimestamp: true,
///   prettyPrintContext: true,
///   showBorders: true,
///   useColors: true,
/// );
/// final controller = StressController(
///   contractAddress: 'erd1...',
///   networkProvider: provider,
///   logger: logger,
/// );
/// ```
class StressController {
  final SmartContractController _controller;

  /// Logger surface for this controller.
  ///
  /// Typed as the abstract [Logger] interface so any subtype passed
  /// to [SmartContractController] flows through unchanged.
  final Logger logger;

  /// Creates controller with contract address.
  StressController({
    required dynamic contractAddress,
    required NetworkProvider networkProvider,
    Logger? logger,
  }) : logger =
           logger ??
           ConsoleLogger(
             minLevel: LogLevel.debug,
             includeTimestamp: true,
             prettyPrintContext: true,
             showBorders: true,
             useColors: true,
           ),
       _controller = SmartContractController(
         abi: abi,
         contractAddress: contractAddress is String
             ? SmartContractAddress.fromBech32(contractAddress)
             : contractAddress as Address,
         networkProvider: networkProvider,
         logger:
             logger ??
             ConsoleLogger(
               minLevel: LogLevel.debug,
               includeTimestamp: true,
               prettyPrintContext: true,
               showBorders: true,
               useColors: true,
             ),
       );

  StressController.withController(this._controller)
    : logger = _controller.logger ?? ConsoleLogger(minLevel: LogLevel.debug);

  SmartContractController get controller => _controller;

  /// Network provider for queries and transactions.
  NetworkProvider get networkProvider => _controller.networkProvider;

  /// Factory for creating unsigned transactions.
  SmartContractCallFactory get factory => SmartContractCallFactory(
    contractAddress: _controller.contractAddress,
    abi: _controller.abi,
    chainId: _controller.networkProvider.chainId,
    logger: _controller.logger,
  );

  Future<TokenPayment> queryReturnStruct() =>
      query_return_struct_query.queryReturnStruct(_controller);

  Future<(int, BigInt, Address)> queryReturnMultiTuple() =>
      query_return_multi_tuple_query.queryReturnMultiTuple(_controller);

  Future<Status> queryReturnEnum() =>
      query_return_enum_query.queryReturnEnum(_controller);

  Future<HttpCode> queryReturnExplicit() =>
      query_return_explicit_query.queryReturnExplicit(_controller);

  Future<void> queryNothing() => query_nothing_query.queryNothing(_controller);

  Future<Transaction> primitiveSoup(
    IAccount sender,
    Nonce nonce,
    int aU8,
    int aI32,
    BigInt aBiguint,
    BigInt aBigint,
    bool aBool,
    Uint8List aBytes,
    String aString,
    Address aAddr,
    TokenIdentifier aTok,
    EgldOrEsdtTokenIdentifier aEgesdt,
    Uint8List aH256,
    List<int> aCode, {
    Address? relayer,
    Address? guardian,
    Balance? value,
  }) => primitive_soup_call.primitiveSoup(
    _controller,
    sender,
    nonce,
    aU8,
    aI32,
    aBiguint,
    aBigint,
    aBool,
    aBytes,
    aString,
    aAddr,
    aTok,
    aEgesdt,
    aH256,
    aCode,
    relayer: relayer,
    guardian: guardian,
    value: value,
  );

  Future<Transaction> collectionSoup(
    IAccount sender,
    Nonce nonce,
    List<int> aList,
    Uint8List aArr3,
    BigInt? aOpt,
    TokenIdentifier? aOptional,
    (int, Address) aTuple,
    List<int> aVariadic,
    (int, Address) aMulti,
    List<BigInt?> aNestedList,
    List<TokenPayment> aListStruct, {
    Address? relayer,
    Address? guardian,
    Balance? value,
  }) => collection_soup_call.collectionSoup(
    _controller,
    sender,
    nonce,
    aList,
    aArr3,
    aOpt,
    aOptional,
    aTuple,
    aVariadic,
    aMulti,
    aNestedList,
    aListStruct,
    relayer: relayer,
    guardian: guardian,
    value: value,
  );

  Future<Transaction> weirdParams(
    IAccount sender,
    Nonce nonce,
    BigInt valueParam,
    Address senderParam,
    int classValue,
    BigInt newValue,
    int field42numeric,
    int controllerParam,
    int factoryValue, {
    Address? relayer,
    Address? guardian,
    Balance? value,
  }) => weird_params_call.weirdParams(
    _controller,
    sender,
    nonce,
    valueParam,
    senderParam,
    classValue,
    newValue,
    field42numeric,
    controllerParam,
    factoryValue,
    relayer: relayer,
    guardian: guardian,
    value: value,
  );

  Future<Transaction> payableOpEgld(
    IAccount sender,
    Nonce nonce, {
    List<TokenTransferValue> tokenTransfers = const <TokenTransferValue>[],
    Address? relayer,
    Address? guardian,
    Balance? value,
  }) => payable_op_egld_call.payableOpEgld(
    _controller,
    sender,
    nonce,
    tokenTransfers: tokenTransfers,
    relayer: relayer,
    guardian: guardian,
    value: value,
  );

  Future<Transaction> payableOpAny(
    IAccount sender,
    Nonce nonce, {
    List<TokenTransferValue> tokenTransfers = const <TokenTransferValue>[],
    Address? relayer,
    Address? guardian,
    Balance? value,
  }) => payable_op_any_call.payableOpAny(
    _controller,
    sender,
    nonce,
    tokenTransfers: tokenTransfers,
    relayer: relayer,
    guardian: guardian,
    value: value,
  );

  Future<Transaction> payableOpSpecific(
    IAccount sender,
    Nonce nonce, {
    List<TokenTransferValue> tokenTransfers = const <TokenTransferValue>[],
    Address? relayer,
    Address? guardian,
    Balance? value,
  }) => payable_op_specific_call.payableOpSpecific(
    _controller,
    sender,
    nonce,
    tokenTransfers: tokenTransfers,
    relayer: relayer,
    guardian: guardian,
    value: value,
  );

  Future<Transaction> emptyMutable(
    IAccount sender,
    Nonce nonce, {
    Address? relayer,
    Address? guardian,
    Balance? value,
  }) => empty_mutable_call.emptyMutable(
    _controller,
    sender,
    nonce,
    relayer: relayer,
    guardian: guardian,
    value: value,
  );

  Future<Transaction> primitiveSoupUnsigned(
    Address sender,
    Nonce nonce,
    int aU8,
    int aI32,
    BigInt aBiguint,
    BigInt aBigint,
    bool aBool,
    Uint8List aBytes,
    String aString,
    Address aAddr,
    TokenIdentifier aTok,
    EgldOrEsdtTokenIdentifier aEgesdt,
    Uint8List aH256,
    List<int> aCode, {
    Balance? value,
  }) => primitive_soup_call.primitiveSoupUnsigned(
    factory,
    networkProvider,
    sender,
    nonce,
    aU8,
    aI32,
    aBiguint,
    aBigint,
    aBool,
    aBytes,
    aString,
    aAddr,
    aTok,
    aEgesdt,
    aH256,
    aCode,
    value: value,
  );

  Future<Transaction> collectionSoupUnsigned(
    Address sender,
    Nonce nonce,
    List<int> aList,
    Uint8List aArr3,
    BigInt? aOpt,
    TokenIdentifier? aOptional,
    (int, Address) aTuple,
    List<int> aVariadic,
    (int, Address) aMulti,
    List<BigInt?> aNestedList,
    List<TokenPayment> aListStruct, {
    Balance? value,
  }) => collection_soup_call.collectionSoupUnsigned(
    factory,
    networkProvider,
    sender,
    nonce,
    aList,
    aArr3,
    aOpt,
    aOptional,
    aTuple,
    aVariadic,
    aMulti,
    aNestedList,
    aListStruct,
    value: value,
  );

  Future<Transaction> weirdParamsUnsigned(
    Address sender,
    Nonce nonce,
    BigInt valueParam,
    Address senderParam,
    int classValue,
    BigInt newValue,
    int field42numeric,
    int controllerParam,
    int factoryValue, {
    Balance? value,
  }) => weird_params_call.weirdParamsUnsigned(
    factory,
    networkProvider,
    sender,
    nonce,
    valueParam,
    senderParam,
    classValue,
    newValue,
    field42numeric,
    controllerParam,
    factoryValue,
    value: value,
  );

  Future<Transaction> payableOpEgldUnsigned(
    Address sender,
    Nonce nonce, {
    List<TokenTransferValue> tokenTransfers = const <TokenTransferValue>[],
    Balance? value,
  }) => payable_op_egld_call.payableOpEgldUnsigned(
    factory,
    networkProvider,
    sender,
    nonce,
    tokenTransfers: tokenTransfers,
    value: value,
  );

  Future<Transaction> payableOpAnyUnsigned(
    Address sender,
    Nonce nonce, {
    List<TokenTransferValue> tokenTransfers = const <TokenTransferValue>[],
    Balance? value,
  }) => payable_op_any_call.payableOpAnyUnsigned(
    factory,
    networkProvider,
    sender,
    nonce,
    tokenTransfers: tokenTransfers,
    value: value,
  );

  Future<Transaction> payableOpSpecificUnsigned(
    Address sender,
    Nonce nonce, {
    List<TokenTransferValue> tokenTransfers = const <TokenTransferValue>[],
    Balance? value,
  }) => payable_op_specific_call.payableOpSpecificUnsigned(
    factory,
    networkProvider,
    sender,
    nonce,
    tokenTransfers: tokenTransfers,
    value: value,
  );

  Future<Transaction> emptyMutableUnsigned(
    Address sender,
    Nonce nonce, {
    Balance? value,
  }) => empty_mutable_call.emptyMutableUnsigned(
    factory,
    networkProvider,
    sender,
    nonce,
    value: value,
  );

  late final StressEvents events = StressEvents(_controller);
}

/// Event streaming accessor
class StressEvents {
  const StressEvents(this._controller);

  final SmartContractController _controller;

  /// Create a unified WebSocket stream for multiple events.
  ///
  /// More efficient than individual streams - uses single WebSocket connection.
  ///
  /// Example:
  /// ```dart
  /// final stream = controller.events.websocketStream(
  ///   websocketUrl: 'wss://kepler-api.projectx.mx/mainnet/events',
  ///   headers: {'Api-Key': 'your-key'},
  /// );
  /// await stream.connect();
  ///
  /// // Listen to specific events
  /// stream.transferEvent.listen((event) => print(event));
  ///
  /// // Or listen to all events
  /// stream.all.listen((event) { ... });
  /// ```
  multi_event_websocket_stream.MultiEventWebSocketStream websocketStream({
    required String websocketUrl,
    Map<String, String> headers = const {},
    bool autoReconnect = true,
    Duration reconnectDelay = const Duration(seconds: 1),
    Duration connectionTimeout = const Duration(seconds: 5),
    Duration pingInterval = const Duration(seconds: 10),
  }) {
    return multi_event_websocket_stream.MultiEventWebSocketStream(
      controller: _controller,
      websocketUrl: websocketUrl,
      headers: headers,
      autoReconnect: autoReconnect,
      reconnectDelay: reconnectDelay,
      connectionTimeout: connectionTimeout,
      pingInterval: pingInterval,
    );
  }

  /// Create a unified polling stream for multiple events.
  ///
  /// More efficient than individual streams - uses single API call.
  ///
  /// Example:
  /// ```dart
  /// final stream = controller.events.pollingStream(
  ///   pollingInterval: Duration(seconds: 10),
  /// );
  ///
  /// // Listen to specific events
  /// stream.transferEvent.listen((event) => print(event));
  ///
  /// // Or listen to all events
  /// stream.all.listen((event) { ... });
  /// ```
  multi_event_polling_stream.MultiEventPollingStream pollingStream({
    Duration pollingInterval = const Duration(seconds: 10),
    String? startFrom,
  }) {
    return multi_event_polling_stream.MultiEventPollingStream(
      controller: _controller,
      pollingInterval: pollingInterval,
      startFrom: startFrom,
    );
  }

  transfer_event_polling_stream.TransferEventPollingStream
  transferEventPolling() =>
      transfer_event_polling_stream.TransferEventPollingStream(_controller);

  transfer_event_websocket_stream.TransferEventWebSocketStream
  transferEventWebSocket({
    required String websocketUrl,
    Map<String, String> headers = const {},
    bool autoReconnect = true,
    Duration reconnectDelay = const Duration(seconds: 5),
    Duration connectionTimeout = const Duration(seconds: 15),
    Duration pingInterval = const Duration(seconds: 30),
  }) {
    return transfer_event_websocket_stream.TransferEventWebSocketStream(
      controller: _controller,
      websocketUrl: websocketUrl,
      headers: headers,
      autoReconnect: autoReconnect,
      reconnectDelay: reconnectDelay,
      connectionTimeout: connectionTimeout,
      pingInterval: pingInterval,
    );
  }

  complex_event_polling_stream.ComplexEventPollingStream
  complexEventPolling() =>
      complex_event_polling_stream.ComplexEventPollingStream(_controller);

  complex_event_websocket_stream.ComplexEventWebSocketStream
  complexEventWebSocket({
    required String websocketUrl,
    Map<String, String> headers = const {},
    bool autoReconnect = true,
    Duration reconnectDelay = const Duration(seconds: 5),
    Duration connectionTimeout = const Duration(seconds: 15),
    Duration pingInterval = const Duration(seconds: 30),
  }) {
    return complex_event_websocket_stream.ComplexEventWebSocketStream(
      controller: _controller,
      websocketUrl: websocketUrl,
      headers: headers,
      autoReconnect: autoReconnect,
      reconnectDelay: reconnectDelay,
      connectionTimeout: connectionTimeout,
      pingInterval: pingInterval,
    );
  }

  marker_only_event_polling_stream.MarkerOnlyEventPollingStream
  markerOnlyEventPolling() =>
      marker_only_event_polling_stream.MarkerOnlyEventPollingStream(
        _controller,
      );

  marker_only_event_websocket_stream.MarkerOnlyEventWebSocketStream
  markerOnlyEventWebSocket({
    required String websocketUrl,
    Map<String, String> headers = const {},
    bool autoReconnect = true,
    Duration reconnectDelay = const Duration(seconds: 5),
    Duration connectionTimeout = const Duration(seconds: 15),
    Duration pingInterval = const Duration(seconds: 30),
  }) {
    return marker_only_event_websocket_stream.MarkerOnlyEventWebSocketStream(
      controller: _controller,
      websocketUrl: websocketUrl,
      headers: headers,
      autoReconnect: autoReconnect,
      reconnectDelay: reconnectDelay,
      connectionTimeout: connectionTimeout,
      pingInterval: pingInterval,
    );
  }
}
