// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by abidock_mvx code generator

import 'package:abidock_mvx/abidock_mvx.dart';

/// Queries getReserve endpoint.
///
/// #### Read-only:
/// Yes
///
/// #### Parameters:
/// - `tokenId`: TokenIdentifier
///
/// #### Returns:
/// - `output`: BigUint
///
/// #### Throws:
/// - [NetworkException] if network request fails
/// - [ABIException] if ABI decoding fails
Future<BigInt> getReserve(
  SmartContractController controller,
  TokenIdentifier tokenId,
) async {
  final tokenIdValue = TokenIdentifierType.type.createValue(tokenId.value);

  return executeQuery(
    endpointName: 'getReserve',
    action: () async {
      final result = await controller.query(
        endpointName: 'getReserve',
        arguments: [tokenIdValue],
      );

      return result.typedValues[0].nativeValue as BigInt;
    },
  );
}
