// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by abidock_mvx code generator

import 'package:abidock_mvx/abidock_mvx.dart';

import '../models/token_pair.dart';

/// Queries getTrustedSwapPairs endpoint.
///
/// #### Read-only:
/// Yes
///
/// #### Returns:
/// - `output`: variadic&lt;tuple&lt;TokenPair,Address&gt;&gt;
///
/// #### Throws:
/// - [NetworkException] if network request fails
/// - [ABIException] if ABI decoding fails
Future<List<(TokenPair, Address)>> getTrustedSwapPairs(
  SmartContractController controller,
) async {
  return executeQuery(
    endpointName: 'getTrustedSwapPairs',
    action: () async {
      final result = await controller.query(
        endpointName: 'getTrustedSwapPairs',
      );

      if (result.isEmpty) {
        return <(TokenPair, Address)>[];
      }
      return (result.typedValues[0] as VariadicValue).items
          .map<(TokenPair, Address)>(
            (e) => (() {
              final t = e as TupleValue;
              return (
                TokenPair.fromAbi(t[0]),
                Address.fromBech32(t[1].nativeValue as String),
              );
            })(),
          )
          .toList();
    },
  );
}
