// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by abidock_mvx code generator

import 'package:abidock_mvx/abidock_mvx.dart';

/// Queries getLpTokenIdentifier endpoint.
///
/// #### Read-only:
/// Yes
///
/// #### Returns:
/// - `output`: TokenIdentifier
///
/// #### Throws:
/// - [NetworkException] if network request fails
/// - [ABIException] if ABI decoding fails
Future<TokenIdentifier> getLpTokenIdentifier(
  SmartContractController controller,
) async {
  return executeQuery(
    endpointName: 'getLpTokenIdentifier',
    action: () async {
      final result = await controller.query(
        endpointName: 'getLpTokenIdentifier',
      );

      return TokenIdentifier(result.typedValues[0].nativeValue as String);
    },
  );
}
