// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by abidock_mvx code generator

import 'package:abidock_mvx/abidock_mvx.dart';

/// Queries getTotalFeePercent endpoint.
///
/// #### Read-only:
/// Yes
///
/// #### Returns:
/// - `output`: u64
///
/// #### Throws:
/// - [NetworkException] if network request fails
/// - [ABIException] if ABI decoding fails
Future<BigInt> getTotalFeePercent(SmartContractController controller) async {
  return executeQuery(
    endpointName: 'getTotalFeePercent',
    action: () async {
      final result = await controller.query(endpointName: 'getTotalFeePercent');

      return result.typedValues[0].nativeValue as BigInt;
    },
  );
}
