// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by abidock_mvx code generator

import 'package:abidock_mvx/abidock_mvx.dart';

/// Queries getEquivalent endpoint.
///
/// #### Read-only:
/// Yes
///
/// #### Parameters:
/// - `tokenIn`: TokenIdentifier
/// - `amountIn`: BigUint
///
/// #### Returns:
/// - `output`: BigUint
///
/// #### Throws:
/// - [NetworkException] if network request fails
/// - [ABIException] if ABI decoding fails
Future<BigInt> getEquivalent(
  SmartContractController controller,
  TokenIdentifier tokenIn,
  BigInt amountIn,
) async {
  final tokenInValue = TokenIdentifierType.type.createValue(tokenIn.value);
  final amountInValue = BigUIntType.type.createValue(amountIn);

  return executeQuery(
    endpointName: 'getEquivalent',
    action: () async {
      final result = await controller.query(
        endpointName: 'getEquivalent',
        arguments: [tokenInValue, amountInValue],
      );

      return result.typedValues[0].nativeValue as BigInt;
    },
  );
}
