// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by abidock_mvx code generator

import 'package:abidock_mvx/abidock_mvx.dart';

/// Queries getFeesCollectorCutPercentage endpoint.
///
/// #### Read-only:
/// Yes
///
/// #### Returns:
/// - `output`: u64
///
/// #### Throws:
/// - [NetworkException] if network request fails
/// - [ABIException] if ABI decoding fails
Future<BigInt> getFeesCollectorCutPercentage(
  SmartContractController controller,
) async {
  return executeQuery(
    endpointName: 'getFeesCollectorCutPercentage',
    action: () async {
      final result = await controller.query(
        endpointName: 'getFeesCollectorCutPercentage',
      );

      return result.typedValues[0].nativeValue as BigInt;
    },
  );
}
