// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by abidock_mvx code generator

import 'package:abidock_mvx/abidock_mvx.dart';

/// Queries getFeeDestinations endpoint.
///
/// #### Read-only:
/// Yes
///
/// #### Returns:
/// - `output`: variadic&lt;tuple&lt;Address,TokenIdentifier&gt;&gt;
///
/// #### Throws:
/// - [NetworkException] if network request fails
/// - [ABIException] if ABI decoding fails
Future<List<(Address, TokenIdentifier)>> getFeeDestinations(
  SmartContractController controller,
) async {
  return executeQuery(
    endpointName: 'getFeeDestinations',
    action: () async {
      final result = await controller.query(endpointName: 'getFeeDestinations');

      if (result.isEmpty) {
        return <(Address, TokenIdentifier)>[];
      }
      return (result.typedValues[0] as VariadicValue).items
          .map<(Address, TokenIdentifier)>(
            (e) => (() {
              final t = e as TupleValue;
              return (
                Address.fromBech32(t[0].nativeValue as String),
                TokenIdentifier(t[1].nativeValue as String),
              );
            })(),
          )
          .toList();
    },
  );
}
