// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by abidock_mvx code generator

import 'package:abidock_mvx/abidock_mvx.dart';

/// Queries getAmountIn endpoint.
///
/// #### Read-only:
/// Yes
///
/// #### Parameters:
/// - `tokenWanted`: TokenIdentifier
/// - `amountWanted`: BigUint
///
/// #### Returns:
/// - `output`: BigUint
///
/// #### Throws:
/// - [NetworkException] if network request fails
/// - [ABIException] if ABI decoding fails
Future<BigInt> getAmountIn(
  SmartContractController controller,
  TokenIdentifier tokenWanted,
  BigInt amountWanted,
) async {
  final tokenWantedValue = TokenIdentifierType.type.createValue(
    tokenWanted.value,
  );
  final amountWantedValue = BigUIntType.type.createValue(amountWanted);

  return executeQuery(
    endpointName: 'getAmountIn',
    action: () async {
      final result = await controller.query(
        endpointName: 'getAmountIn',
        arguments: [tokenWantedValue, amountWantedValue],
      );

      return result.typedValues[0].nativeValue as BigInt;
    },
  );
}
