// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by abidock_mvx code generator

import 'package:abidock_mvx/abidock_mvx.dart';

/// Queries getRouterManagedAddress endpoint.
///
/// #### Read-only:
/// Yes
///
/// #### Returns:
/// - `output`: Address
///
/// #### Throws:
/// - [NetworkException] if network request fails
/// - [ABIException] if ABI decoding fails
Future<Address> getRouterManagedAddress(
  SmartContractController controller,
) async {
  return executeQuery(
    endpointName: 'getRouterManagedAddress',
    action: () async {
      final result = await controller.query(
        endpointName: 'getRouterManagedAddress',
      );

      return Address.fromBech32(result.typedValues[0].nativeValue as String);
    },
  );
}
