// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by abidock_mvx code generator

import 'package:abidock_mvx/abidock_mvx.dart';

/// Queries getPermissions endpoint.
///
/// #### Read-only:
/// Yes
///
/// #### Parameters:
/// - `address`: Address
///
/// #### Returns:
/// - `output`: u32
///
/// #### Throws:
/// - [NetworkException] if network request fails
/// - [ABIException] if ABI decoding fails
Future<int> getPermissions(
  SmartContractController controller,
  Address address,
) async {
  final addressValue = AddressType.type.createValue(address.bech32);

  return executeQuery(
    endpointName: 'getPermissions',
    action: () async {
      final result = await controller.query(
        endpointName: 'getPermissions',
        arguments: [addressValue],
      );

      return result.typedValues[0].nativeValue as int;
    },
  );
}
