// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by abidock_mvx code generator

import 'package:abidock_mvx/abidock_mvx.dart';

/// Queries getWhitelistedManagedAddresses endpoint.
///
/// #### Read-only:
/// Yes
///
/// #### Returns:
/// - `output`: variadic&lt;Address&gt;
///
/// #### Throws:
/// - [NetworkException] if network request fails
/// - [ABIException] if ABI decoding fails
Future<List<Address>> getWhitelistedManagedAddresses(
  SmartContractController controller,
) async {
  return executeQuery(
    endpointName: 'getWhitelistedManagedAddresses',
    action: () async {
      final result = await controller.query(
        endpointName: 'getWhitelistedManagedAddresses',
      );

      if (result.isEmpty) {
        return <Address>[];
      }
      return (result.typedValues[0] as VariadicValue).items
          .map<Address>((e) => Address.fromBech32(e.nativeValue as String))
          .toList();
    },
  );
}
