// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by abidock_mvx code generator

import 'package:abidock_mvx/abidock_mvx.dart';

/// Queries getInitialLiquidtyAdder endpoint.
///
/// #### Read-only:
/// Yes
///
/// #### Returns:
/// - `output`: Option&lt;Address&gt;
///
/// #### Throws:
/// - [NetworkException] if network request fails
/// - [ABIException] if ABI decoding fails
Future<Address?> getInitialLiquidtyAdder(
  SmartContractController controller,
) async {
  return executeQuery(
    endpointName: 'getInitialLiquidtyAdder',
    action: () async {
      final result = await controller.query(
        endpointName: 'getInitialLiquidtyAdder',
      );

      return (() {
        final v = result.typedValues[0] as OptionValue;
        return v.value == null
            ? null
            : Address.fromBech32(v.value!.nativeValue as String);
      })();
    },
  );
}
